// Generates src/data/camSources.ts, the Worker's slice of the camera master.
//
//   npm run cams:sources   # → src/data/camSources.ts (no network; reads src/data/cams.ts)
//
// cams:build runs this too, so it only needs running by hand after editing cams.ts directly.
// src/data/camSources.test.ts fails when the two drift apart.
//
// Why a separate file: the Cron runs under the free plan's 10ms CPU limit, and evaluating
// the 3.2MB object literal of the full master took about 35ms of each run (measured
// 2026-10-04). The Worker reads only id and source. The slice is also emitted as a JSON
// string, because V8 parses JSON faster than it evaluates the same object literal.

import { writeFile } from "node:fs/promises";

type CamLike = { id: string; source: { videoId: string | null; channelId: string; titleKey: string } };

/** id and source only, with source's keys in a fixed order. */
export function camSources(cams: readonly CamLike[]): CamLike[] {
  return cams.map(({ id, source }) => ({
    id,
    source: { videoId: source.videoId, channelId: source.channelId, titleKey: source.titleKey },
  }));
}

export function serializeCamSources(cams: readonly CamLike[]): string {
  const json = JSON.stringify(camSources(cams));
  return `// Generated by scripts/build-cam-sources.ts. Do not edit by hand.
// Generate: npm run cams:sources (cams:build runs it too)
//
// The Worker's slice of src/data/cams.ts: id and source only. The Cron runs under a 10ms CPU
// limit, and evaluating the full master cost about 35ms of it.

import type { CamRef } from "../domain/cams";

export const CAM_SOURCES: readonly CamRef[] = JSON.parse(${JSON.stringify(json)});
`;
}

export async function writeCamSources(cams: readonly CamLike[]): Promise<void> {
  await writeFile("src/data/camSources.ts", serializeCamSources(cams));
  console.log(`✓ wrote ${cams.length} camera sources to src/data/camSources.ts`);
}

if (import.meta.url === `file://${process.argv[1]}`) {
  // Imported here, not at the top: cams:build imports this module before it rewrites
  // cams.ts, and a top-level import would hand it the stale master.
  const { CAMS } = await import("../src/data/cams.ts");
  await writeCamSources(CAMS);
}
