// Generates src/data/cams.ts from cam-places.ts (manual curation) and
// cam-places-bulk.ts (bulk import).
//
//   npm run cams:discover   # first fetch the list of channels and live streams
//   npm run cams:build      # → src/data/cams.ts and src/data/camSources.ts
//
// Coordinates and time zones are resolved with Open-Meteo geocoding (no key needed).
// To avoid mixing up towns with the same name, results are narrowed by admin1; if nothing
// matches, it is reported as a failure and a different place is never silently adopted.
//
// Embeddability: manually curated entries are checked every time. Bulk-imported entries
// were already filtered by camlisted's embeddable=true at import time, so they are skipped here
// (querying YouTube one by one at the scale of 3000 entries does not finish in a realistic time).

import { writeFile } from "node:fs/promises";
import { writeCamSources } from "./build-cam-sources.ts";
import { CAM_PLACES_CURATED, type CamPlace } from "./cam-places.ts";
import { CAM_PLACES_BULK } from "./cam-places-bulk.ts";

const CAM_PLACES: CamPlace[] = [
  ...(CAM_PLACES_CURATED as CamPlace[]),
  ...(CAM_PLACES_BULK as CamPlace[]),
];

const BULK_IDS = new Set(CAM_PLACES_BULK.map((p) => p.id));

const GEOCODE_DELAY_MS = 400;
const EMBED_CONCURRENCY = 12;

const UA =
  "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 " +
  "(KHTML, like Gecko) Chrome/120.0 Safari/537.36";

/**
 * Whether playback on external sites is allowed.
 *
 * Two kinds of "no" must be distinguished:
 *   forbidden … the owner has prohibited embedding. It is a permanent property, so **drop** it
 *               (SkylineWebcams is this case. Opening it only shows "cannot be played").
 *   unknown   … the stream is gone and cannot be judged. The camera itself may still be
 *               alive, so **keep** it. The Worker's rediscovery finds the next stream
 *               using the title as a clue. Dropping it here loses the camera forever.
 */
type Embeddability = "allowed" | "forbidden" | "unknown";

async function embeddabilityOf(videoId: string): Promise<Embeddability> {
  try {
    const res = await fetch(`https://www.youtube.com/watch?v=${videoId}`, {
      headers: { "user-agent": UA, "accept-language": "en-US,en" },
    });
    if (!res.ok) return "unknown";
    const match = /"playableInEmbed":(true|false)/.exec(await res.text());
    if (match === null) return "unknown";
    return match[1] === "true" ? "allowed" : "forbidden";
  } catch {
    return "unknown";
  }
}

interface GeocodeHit {
  latitude: number;
  longitude: number;
  timezone: string;
  country_code: string;
  admin1?: string;
  name: string;
}

interface Resolved {
  place: CamPlace;
  lat: number;
  lng: number;
  timeZone: string;
  country: string;
  /** Where the coordinates came from. Kept in a comment of the generated file. */
  origin: string;
}

async function geocode(query: NonNullable<CamPlace["place"]>): Promise<GeocodeHit> {
  const url =
    "https://geocoding-api.open-meteo.com/v1/search" +
    `?name=${encodeURIComponent(query.name)}&count=10&language=en` +
    `&countryCode=${query.countryCode}`;

  const res = await fetch(url);
  if (!res.ok) throw new Error(`geocoding failed HTTP ${res.status}`);

  const results = ((await res.json()) as { results?: GeocodeHit[] }).results ?? [];
  if (results.length === 0) throw new Error(`no match: ${query.name}`);

  if (query.admin1 === undefined) return results[0]!;

  const hit = results.find((r) => r.admin1 === query.admin1);
  if (hit === undefined) {
    const seen = [...new Set(results.map((r) => r.admin1 ?? "?"))].join(", ");
    throw new Error(`admin1 does not match (expected: ${query.admin1} / candidates: ${seen})`);
  }
  return hit;
}

function serialize(resolved: readonly Resolved[]): string {
  const entries = resolved
    .map(({ place, lat, lng, timeZone, country, origin }) => {
      const p = place;
      return `  {
    // ${origin}
    id: ${JSON.stringify(p.id)},
    name: { ja: ${JSON.stringify(p.nameJa)}, en: ${JSON.stringify(p.nameEn)} },
    lat: ${lat},
    lng: ${lng},
    timeZone: ${JSON.stringify(timeZone)},
    category: ${JSON.stringify(p.category)},
    country: ${JSON.stringify(country)},
    source: {
      videoId: ${JSON.stringify(p.videoId)},
      channelId: ${JSON.stringify(p.channelId)},
      titleKey: ${JSON.stringify(p.titleKey)},
    },
  },`;
    })
    .join("\n");

  return `// Generated by scripts/build-cams.ts. Do not edit by hand.
// Sources: scripts/cam-places.ts (hand-curated)
//          scripts/cam-places-bulk.ts (bulk import)
// Generate: npm run cams:import-bulk && npm run cams:build
//
// videoId is the stream that was live at generation time. When the stream changes,
// the Worker's rediscovery resolves the current one from titleKey, so the map does
// not die when this file goes stale.
// titleKey is the stream title of that camera. It is needed to tell the target
// camera apart when one channel runs dozens of them.

import type { Cam } from "../domain/cams";

export const CAMS: Cam[] = [
${entries}
];
`;
}

async function resolvePlace(
  place: CamPlace,
  embeddability: Embeddability,
): Promise<{ resolved?: Resolved; failure?: string; warning?: string }> {
  if (embeddability === "forbidden") {
    return { failure: `[${place.id}] dropped because embedded playback is forbidden (owner's setting)` };
  }
  const warning =
    embeddability === "unknown"
      ? `[${place.id}] the recorded stream is gone. The camera is kept, so rediscovery looks for the next stream`
      : undefined;

  if (place.at !== undefined) {
    return {
      resolved: {
        place,
        ...place.at,
        origin: "coords: set explicitly as a well-known landmark",
      },
      warning,
    };
  }

  try {
    const hit = await geocode(place.place!);
    return {
      resolved: {
        place,
        lat: Number(hit.latitude.toFixed(4)),
        lng: Number(hit.longitude.toFixed(4)),
        timeZone: hit.timezone,
        country: hit.country_code,
        origin: `coords: Open-Meteo geocoding "${hit.name}"${hit.admin1 === undefined ? "" : `, ${hit.admin1}`}`,
      },
      warning,
    };
  } catch (error) {
    return { failure: `[${place.id}] ${String(error)}`, warning };
  }
}

async function mapPool<T, R>(
  items: readonly T[],
  concurrency: number,
  fn: (item: T) => Promise<R>,
): Promise<R[]> {
  const results: R[] = new Array(items.length);
  let next = 0;
  async function worker(): Promise<void> {
    while (next < items.length) {
      const i = next++;
      results[i] = await fn(items[i]!);
    }
  }
  await Promise.all(Array.from({ length: Math.min(concurrency, items.length) }, () => worker()));
  return results;
}

async function main(): Promise<void> {
  const resolved: Resolved[] = [];
  const failures: string[] = [];
  const warnings: string[] = [];

  const curated = CAM_PLACES.filter((p) => !BULK_IDS.has(p.id));
  const curatedVideoIds = new Set(curated.map((p) => p.videoId));
  // For streams re-placed by hand, drop the duplicate pin on the bulk side
  const bulk = CAM_PLACES.filter(
    (p) => BULK_IDS.has(p.id) && !curatedVideoIds.has(p.videoId),
  );

  // Check embeddability only for curated entries (in parallel). bulk was already
  // filtered by embeddable at import.
  const curatedResults = await mapPool(curated, EMBED_CONCURRENCY, async (place) => {
    const embeddability = await embeddabilityOf(place.videoId);
    if (place.place !== undefined) {
      await new Promise((r) => setTimeout(r, GEOCODE_DELAY_MS));
    }
    return resolvePlace(place, embeddability);
  });

  for (const result of curatedResults) {
    if (result.warning !== undefined) warnings.push(result.warning);
    if (result.failure !== undefined) failures.push(result.failure);
    else if (result.resolved !== undefined) resolved.push(result.resolved);
  }

  for (const place of bulk) {
    const result = await resolvePlace(place, "allowed");
    if (result.failure !== undefined) failures.push(result.failure);
    else if (result.resolved !== undefined) resolved.push(result.resolved);
  }

  await writeFile("src/data/cams.ts", serialize(resolved));
  // First import of cams.ts in this process, so it reads the file just written.
  const { CAMS } = await import("../src/data/cams.ts");
  await writeCamSources(CAMS);

  console.log(`✓ wrote ${resolved.length} cameras to src/data/cams.ts`);
  if (warnings.length > 0) {
    console.log(`\n△ kept but needs attention: ${warnings.length}:`);
    for (const w of warnings) console.log(`  ${w}`);
  }
  if (failures.length > 0) {
    console.log(`\n✗ could not be imported: ${failures.length}:`);
    for (const f of failures) console.log(`  ${f}`);
  }
}

await main();
