// discover-cams.ts が集めた候補のうち、地理が一意に定まるものだけを人手で選び、
// 場所の情報を与えた表。これが src/data/cams.ts の元になる。
//
// channelId と titleKey は discover が実際に取ってきた値を**ここに固定する**。
// 毎回のスクレイプ結果を参照すると、たまたま配信が落ちていたカメラがビルドの
// たびにマスタから消える(実際に起きた)。キュレーションの記録は、その時どきの
// 配信状況から独立していなければならない。
//
// 座標の出どころは 2 通りで、どちらも「記憶で書いた数字」にしないのが方針:
//   place … Open-Meteo のジオコーディングで解決する(小さな町はこちら。町の中心が
//           実質そのままカメラの位置になる)。admin1 は同名地の取り違え防止。
//   at    … 誰でも地図で確かめられる著名なランドマークだけ、明示的に置く。

import type { CamCategory } from "../src/domain/cams";

export interface PlaceQuery {
  name: string;
  countryCode: string;
  /** 州・県名。同名の町を取り違えないための絞り込み。 */
  admin1?: string;
}

export interface CamPlace {
  id: string;
  nameJa: string;
  nameEn: string;
  category: CamCategory;
  /** 人が読むための出どころ。discover-cams.ts の出力にあるハンドル。 */
  handle: string;
  /** 機械が解決した値をここに固定する(毎回のスクレイプに依存させない)。 */
  channelId: string;
  videoId: string;
  /**
   * 配信タイトル。1 チャンネルに何十台もぶら下がるので、再探索で
   * 「どれがこのカメラか」を見分ける鍵になる。
   */
  titleKey: string;
  place?: PlaceQuery;
  at?: { lat: number; lng: number; timeZone: string; country: string };
}

export const CAM_PLACES: CamPlace[] = [
  // ── 日本 ────────────────────────────────────────────────
  {
    id: "shibuya-crossing",
    nameJa: "渋谷スクランブル交差点",
    nameEn: "Shibuya Scramble Crossing",
    category: "city",
    handle: "ANNnewsCH",
    channelId: "UCGCZAYq5Xxojl_tSXcVJhiQ",
    videoId: "8H3nRCFVR6Y",
    titleKey: "【ライブ】渋谷スクランブル交差点 / Shibuya Scramble Crossing Live Camera【LIVE】ANN/テレ朝",
    at: { lat: 35.6595, lng: 139.7005, timeZone: "Asia/Tokyo", country: "JP" },
  },
  {
    id: "shinjuku-station",
    nameJa: "新宿駅前",
    nameEn: "Shinjuku Station",
    category: "city",
    handle: "tbsnewsdig",
    channelId: "UC6AG81pAkf6Lbi_1VC5NmPA",
    videoId: "BePkAsZnDjM",
    titleKey: "【LIVE】新宿駅前のライブカメラ 現在の様子は？ Shinjuku, Tokyo JAPAN | TBS NEWS DIG",
    at: { lat: 35.6900, lng: 139.7004, timeZone: "Asia/Tokyo", country: "JP" },
  },
  {
    id: "haneda-terminal-2",
    nameJa: "羽田空港 第2ターミナル",
    nameEn: "Haneda Airport Terminal 2",
    category: "airport",
    handle: "ANNnewsCH",
    channelId: "UCGCZAYq5Xxojl_tSXcVJhiQ",
    videoId: "OyWPJhU-iI8",
    titleKey: "【ライブ】羽田空港第2ターミナルを24時間配信中！  HANEDA,Tokyo International Airport Terminal2【LIVE】ANN/テレ朝",
    at: { lat: 35.5494, lng: 139.7798, timeZone: "Asia/Tokyo", country: "JP" },
  },
  {
    id: "haneda-terminal-1",
    nameJa: "羽田空港 第1ターミナル",
    nameEn: "Haneda Airport Terminal 1",
    category: "airport",
    handle: "tbsnewsdig",
    channelId: "UC6AG81pAkf6Lbi_1VC5NmPA",
    videoId: "2f9NOSw-FqM",
    titleKey: "【ライブ】羽田空港 第1ターミナルのライブカメラ 現在の様子は？Haneda Airport's Terminal 1| TBS NEWS DIG",
    at: { lat: 35.5490, lng: 139.7855, timeZone: "Asia/Tokyo", country: "JP" },
  },

  // ── ヨーロッパ ──────────────────────────────────────────
  {
    id: "abbey-road-crossing",
    nameJa: "アビイ・ロードの横断歩道",
    nameEn: "Abbey Road Crossing",
    category: "city",
    handle: "EarthCam",
    channelId: "UC6qrG3W8SMK0jior2olka3g",
    videoId: "zMCea32gpmg",
    titleKey: "EarthCam Live:  Abbey Road Crossing (London, England)",
    at: { lat: 51.5320, lng: -0.1779, timeZone: "Europe/London", country: "GB" },
  },
  {
    id: "mallorca",
    nameJa: "マヨルカ島",
    nameEn: "Mallorca",
    category: "harbor",
    handle: "EarthCam",
    channelId: "UC6qrG3W8SMK0jior2olka3g",
    videoId: "jtdyLykT_XY",
    titleKey: "EarthCam Live:  Mallorca, Spain",
    place: { name: "Palma", countryCode: "ES", admin1: "Balearic Islands" },
  },

  // ── 北米 (都市・ランドマーク) ───────────────────────────
  {
    id: "times-square",
    nameJa: "タイムズスクエア",
    nameEn: "Times Square",
    category: "city",
    handle: "EarthCam",
    channelId: "UC6qrG3W8SMK0jior2olka3g",
    videoId: "JQ_jwk_7OVE",
    titleKey: "EarthCam Live:  Times Square North 4K",
    at: { lat: 40.7580, lng: -73.9855, timeZone: "America/New_York", country: "US" },
  },
  {
    id: "statue-of-liberty",
    nameJa: "自由の女神(冠のカメラ)",
    nameEn: "Statue of Liberty CrownCam",
    category: "city",
    handle: "EarthCam",
    channelId: "UC6qrG3W8SMK0jior2olka3g",
    videoId: "YHRYOL03ydw",
    titleKey: "EarthCam Live:  Statue of Liberty CrownCam",
    at: { lat: 40.6892, lng: -74.0445, timeZone: "America/New_York", country: "US" },
  },
  {
    id: "world-trade-center",
    nameJa: "ワールドトレードセンター",
    nameEn: "World Trade Center",
    category: "city",
    handle: "EarthCam",
    channelId: "UC6qrG3W8SMK0jior2olka3g",
    videoId: "5C9oM7C2Q9k",
    titleKey: "EarthCam Live:  World Trade Center - New York City, NY",
    at: { lat: 40.7127, lng: -74.0134, timeZone: "America/New_York", country: "US" },
  },
  {
    id: "lincoln-harbor",
    nameJa: "リンカーン・ハーバー(マンハッタン対岸)",
    nameEn: "Lincoln Harbor",
    category: "harbor",
    handle: "EarthCam",
    channelId: "UC6qrG3W8SMK0jior2olka3g",
    videoId: "f_pX8XheLbY",
    titleKey: "EarthCam Live:  Lincoln Harbor (New York City)",
    at: { lat: 40.7690, lng: -74.0170, timeZone: "America/New_York", country: "US" },
  },
  {
    id: "white-house",
    nameJa: "ホワイトハウス",
    nameEn: "The White House",
    category: "city",
    handle: "earthTV",
    channelId: "UCRuyAVeVd7oUwh0LWmxxBBQ",
    videoId: "5p_KGD4fJZs",
    titleKey: "earthTV® White House Cam is back!",
    at: { lat: 38.8977, lng: -77.0365, timeZone: "America/New_York", country: "US" },
  },
  {
    id: "washington-monument",
    nameJa: "ワシントン記念塔",
    nameEn: "Washington Monument",
    category: "city",
    handle: "EarthCam",
    channelId: "UC6qrG3W8SMK0jior2olka3g",
    videoId: "oDCAAfOSqvA",
    titleKey: "EarthCam Live:  Washington Monument (Washington, D.C.)",
    at: { lat: 38.8895, lng: -77.0353, timeZone: "America/New_York", country: "US" },
  },
  {
    id: "independence-hall",
    nameJa: "独立記念館とリバティ・ベル",
    nameEn: "Liberty Bell & Independence Hall",
    category: "city",
    handle: "EarthCam",
    channelId: "UC6qrG3W8SMK0jior2olka3g",
    videoId: "F1EQEDL4ddU",
    titleKey: "EarthCam Live:  Liberty Bell - Independence Hall (Philadelphia, PA)",
    at: { lat: 39.9489, lng: -75.1500, timeZone: "America/New_York", country: "US" },
  },
  {
    id: "wrigley-field",
    nameJa: "リグレー・フィールド(シカゴ)",
    nameEn: "Wrigley Field",
    category: "city",
    handle: "EarthCam",
    channelId: "UC6qrG3W8SMK0jior2olka3g",
    videoId: "m38n8jVPUJ8",
    titleKey: "EarthCam Live:  Wrigley Field",
    at: { lat: 41.9484, lng: -87.6553, timeZone: "America/Chicago", country: "US" },
  },
  {
    id: "new-orleans-balcony",
    nameJa: "ニューオーリンズ(バルコニーからの眺め)",
    nameEn: "New Orleans Balcony View",
    category: "city",
    handle: "EarthCam",
    channelId: "UC6qrG3W8SMK0jior2olka3g",
    videoId: "6lFBKxt8kIo",
    titleKey: "EarthCam Live: New Orleans Balcony View",
    place: { name: "New Orleans", countryCode: "US", admin1: "Louisiana" },
  },
  {
    id: "flight-93-memorial",
    nameJa: "ユナイテッド93便記念碑",
    nameEn: "Flight 93 Memorial",
    category: "nature",
    handle: "EarthCam",
    channelId: "UC6qrG3W8SMK0jior2olka3g",
    videoId: "mjzA1Yxh7ZY",
    titleKey: "EarthCam Live:  Flight 93 Memorial - Tower of Voices (Shanksville, PA)",
    place: { name: "Shanksville", countryCode: "US", admin1: "Pennsylvania" },
  },
  {
    id: "madison-indiana",
    nameJa: "マディソン(インディアナ)",
    nameEn: "Madison, Indiana",
    category: "city",
    handle: "EarthCam",
    channelId: "UC6qrG3W8SMK0jior2olka3g",
    videoId: "Ez6xC43MMTQ",
    titleKey: "EarthCam Live:  Madison, Indiana",
    place: { name: "Madison", countryCode: "US", admin1: "Indiana" },
  },
  {
    id: "council-bluffs",
    nameJa: "カウンシルブラフス(アイオワ)",
    nameEn: "Council Bluffs, Iowa",
    category: "city",
    handle: "EarthCam",
    channelId: "UC6qrG3W8SMK0jior2olka3g",
    videoId: "qsrevo5Vdkw",
    titleKey: "EarthCam Live:  Council Bluffs, Iowa",
    place: { name: "Council Bluffs", countryCode: "US", admin1: "Iowa" },
  },
  {
    id: "jamestown-buffalo",
    nameJa: "世界最大のバッファロー像(ジェームズタウン)",
    nameEn: "World's Largest Buffalo Monument",
    category: "city",
    handle: "EarthCam",
    channelId: "UC6qrG3W8SMK0jior2olka3g",
    videoId: "VWDi2Po3ZsQ",
    titleKey: "EarthCam Live:  World's Largest Buffalo Monument (Jamestown, North Dakota)",
    place: { name: "Jamestown", countryCode: "US", admin1: "North Dakota" },
  },
  {
    id: "roswell",
    nameJa: "ロズウェル(ニューメキシコ)",
    nameEn: "Roswell, New Mexico",
    category: "city",
    handle: "EarthCam",
    channelId: "UC6qrG3W8SMK0jior2olka3g",
    videoId: "kLoFxVhRWtQ",
    titleKey: "EarthCam Live:  Roswell, New Mexico",
    place: { name: "Roswell", countryCode: "US", admin1: "New Mexico" },
  },
  {
    id: "ruidoso",
    nameJa: "ルイドソ(ニューメキシコ)",
    nameEn: "Ruidoso, New Mexico",
    category: "nature",
    handle: "EarthCam",
    channelId: "UC6qrG3W8SMK0jior2olka3g",
    videoId: "XoANQufSSXY",
    titleKey: "EarthCam Live:  Ruidoso, New Mexico",
    place: { name: "Ruidoso", countryCode: "US", admin1: "New Mexico" },
  },

  // ── 北米 (自然・海) ────────────────────────────────────
  {
    id: "sanibel-island",
    nameJa: "サニベル島",
    nameEn: "Sanibel Island",
    category: "nature",
    handle: "EarthCam",
    channelId: "UC6qrG3W8SMK0jior2olka3g",
    videoId: "4LTSTw4jnZc",
    titleKey: "EarthCam Live:  Sanibel Island",
    place: { name: "Sanibel", countryCode: "US", admin1: "Florida" },
  },
  {
    id: "anglins-pier",
    nameJa: "アングリンズ桟橋(フロリダ)",
    nameEn: "Anglins Pier",
    category: "harbor",
    handle: "EarthCam",
    channelId: "UC6qrG3W8SMK0jior2olka3g",
    videoId: "aPo-gk0y9tg",
    titleKey: "EarthCam Live:  Anglins Pier (Lauderdale-By-The-Sea, FL)",
    place: { name: "Lauderdale-by-the-Sea", countryCode: "US", admin1: "Florida" },
  },
  {
    id: "seaside-heights",
    nameJa: "シーサイドハイツ(ニュージャージー)",
    nameEn: "Seaside Heights, NJ",
    category: "nature",
    handle: "EarthCam",
    channelId: "UC6qrG3W8SMK0jior2olka3g",
    videoId: "OBgCrw-IyhE",
    titleKey: "EarthCam Live:  Seaside Heights, NJ - North View",
    place: { name: "Seaside Heights", countryCode: "US", admin1: "New Jersey" },
  },
  {
    id: "wildwood",
    nameJa: "ワイルドウッド(ニュージャージー)",
    nameEn: "Wildwood, NJ",
    category: "nature",
    handle: "EarthCam",
    channelId: "UC6qrG3W8SMK0jior2olka3g",
    videoId: "cK71xhMRtds",
    titleKey: "EarthCam Live:  Wildwoods Cam (Wildwood, NJ)",
    place: { name: "Wildwood", countryCode: "US", admin1: "New Jersey" },
  },
  {
    id: "spirit-lake",
    nameJa: "スピリット湖(アイオワ)",
    nameEn: "Spirit Lake, Iowa",
    category: "nature",
    handle: "EarthCam",
    channelId: "UC6qrG3W8SMK0jior2olka3g",
    videoId: "XIe9vQkAd7Q",
    titleKey: "EarthCam Live:  Spirit Lake, Iowa",
    place: { name: "Spirit Lake", countryCode: "US", admin1: "Iowa" },
  },

  // ── 北米 (動物) ────────────────────────────────────────
  {
    id: "monterey-sea-otter",
    nameJa: "モントレー湾水族館 ラッコ",
    nameEn: "Monterey Bay Aquarium — Sea Otters",
    category: "animal",
    handle: "MontereyBayAquarium",
    channelId: "UCnM5iMGiKsZg-iOlIO2ZkdQ",
    videoId: "abbR-Ttd-cA",
    titleKey: "Live Sea Otter Cam | Monterey Bay Aquarium",
    at: { lat: 36.6182, lng: -121.9018, timeZone: "America/Los_Angeles", country: "US" },
  },
  {
    id: "monterey-bay",
    nameJa: "モントレー湾",
    nameEn: "Monterey Bay",
    category: "nature",
    handle: "MontereyBayAquarium",
    channelId: "UCnM5iMGiKsZg-iOlIO2ZkdQ",
    videoId: "fVa6-zCBR7A",
    titleKey: "Live Monterey Bay Cam | Monterey Bay Aquarium",
    at: { lat: 36.6182, lng: -121.9018, timeZone: "America/Los_Angeles", country: "US" },
  },
  {
    id: "baltimore-aquarium",
    nameJa: "ボルチモア水族館",
    nameEn: "National Aquarium, Baltimore",
    category: "animal",
    handle: "EarthCam",
    channelId: "UC6qrG3W8SMK0jior2olka3g",
    videoId: "KSxc-N67TU4",
    titleKey: "EarthCam Live:  Aquarium Cam (Baltimore, Maryland)",
    place: { name: "Baltimore", countryCode: "US", admin1: "Maryland" },
  },
  {
    id: "greenville-giraffe",
    nameJa: "グリーンビル動物園 キリン",
    nameEn: "Greenville Zoo — Giraffes",
    category: "animal",
    handle: "EarthCam",
    channelId: "UC6qrG3W8SMK0jior2olka3g",
    videoId: "sLRtUoPNH2k",
    titleKey: "EarthCam Live:  Giraffe Paddock  Cam - Greenville, SC",
    place: { name: "Greenville", countryCode: "US", admin1: "South Carolina" },
  },
  {
    id: "gaylord-wildlife",
    nameJa: "ゲイロード(ミシガン)の野生動物",
    nameEn: "Gaylord Wildlife Cam",
    category: "animal",
    handle: "EarthCam",
    channelId: "UC6qrG3W8SMK0jior2olka3g",
    videoId: "IU_-Pl9O5jQ",
    titleKey: "EarthCam Live: Snowman Cam - Animals and Wildlife (Gaylord, Michigan)",
    place: { name: "Gaylord", countryCode: "US", admin1: "Michigan" },
  },

  // ── アフリカ・南米 ──────────────────────────────────────
  {
    id: "chobe-waterhole",
    nameJa: "チョベ(ボツワナ)の水場",
    nameEn: "Chobe Watering Hole, Botswana",
    category: "animal",
    handle: "EarthCam",
    channelId: "UC6qrG3W8SMK0jior2olka3g",
    videoId: "iqdRLSdSjWI",
    titleKey: "EarthCam Live:  Hideaways Camp Kuzuma, African Watering Hole (Chobe, Botswana)",
    place: { name: "Kasane", countryCode: "BW" },
  },
  {
    id: "rio-negro-amazon",
    nameJa: "アマゾン ネグロ川",
    nameEn: "Rio Negro, Amazon",
    category: "nature",
    handle: "ANNnewsCH",
    channelId: "UCGCZAYq5Xxojl_tSXcVJhiQ",
    videoId: "zAZ6S9pv0jA",
    titleKey: "【LIVE】癒しの熱帯 アマゾンのジャングルから配信　夜明けの空を横切るインコの群れ　夜の川に響くカエルと昆虫の声　#ネグロ川 #ブラジル【ライブ】ANN/テレ朝",
    place: { name: "Manaus", countryCode: "BR" },
  },

  // ── メキシコ ───────────────────────────────────────────
  {
    id: "popocatepetl",
    nameJa: "ポポカテペトル山",
    nameEn: "Popocatépetl Volcano",
    category: "volcano",
    handle: "webcamsdemexico",
    channelId: "UColBcWm6ybTbQnNuQS8JaKg",
    videoId: "z1DIktum4zo",
    titleKey: "🌋 #POPOCATÉPETL | 🛸 Los objetos salen de su garita esta noche. El #volcán #EnVivo",
    at: { lat: 19.0224, lng: -98.6279, timeZone: "America/Mexico_City", country: "MX" },
  },
  {
    id: "cdmx-zocalo",
    nameJa: "メキシコシティ ソカロ広場",
    nameEn: "Zócalo, Mexico City",
    category: "city",
    handle: "webcamsdemexico",
    channelId: "UColBcWm6ybTbQnNuQS8JaKg",
    videoId: "qP-b5q9u018",
    titleKey: "En vivo Zócalo de la Ciudad de México",
    at: { lat: 19.4326, lng: -99.1332, timeZone: "America/Mexico_City", country: "MX" },
  },
  {
    id: "cdmx-angel",
    nameJa: "独立記念塔(メキシコシティ)",
    nameEn: "Ángel de la Independencia",
    category: "city",
    handle: "webcamsdemexico",
    channelId: "UColBcWm6ybTbQnNuQS8JaKg",
    videoId: "ZH3jB650mcI",
    titleKey: "Paseo de la Reforma en vivo. Monumento Ángel de la Independencia",
    at: { lat: 19.4270, lng: -99.1677, timeZone: "America/Mexico_City", country: "MX" },
  },
  {
    id: "basilica-guadalupe",
    nameJa: "グアダルーペ聖堂",
    nameEn: "Basilica of Guadalupe",
    category: "city",
    handle: "webcamsdemexico",
    channelId: "UColBcWm6ybTbQnNuQS8JaKg",
    videoId: "NmHkMgNwawg",
    titleKey: "Basílica de Guadalupe, Ciudad de México, en vivo",
    at: { lat: 19.4847, lng: -99.1177, timeZone: "America/Mexico_City", country: "MX" },
  },

  // ── ジャクソンホール周辺(ワイオミング・モンタナ) ────────
  {
    id: "jackson-town-square",
    nameJa: "ジャクソン タウンスクエア",
    nameEn: "Jackson Town Square",
    category: "city",
    handle: "SeeJH",
    channelId: "UCEpDjqeFIGTqHwk-uULx72Q",
    videoId: "B_waF26In9o",
    titleKey: "Jackson Town Square Live PTZ webcam - SeeJH.ai",
    at: { lat: 43.4799, lng: -110.7624, timeZone: "America/Denver", country: "US" },
  },
  {
    id: "grand-teton",
    nameJa: "グランドティトン国立公園",
    nameEn: "Grand Teton National Park",
    category: "nature",
    handle: "SeeJH",
    channelId: "UCEpDjqeFIGTqHwk-uULx72Q",
    videoId: "j-0fhrHzEiM",
    titleKey: "EGVB - Grand Teton Webcam",
    at: { lat: 43.7412, lng: -110.8025, timeZone: "America/Denver", country: "US" },
  },
  {
    id: "yellowstone-river-gardiner",
    nameJa: "イエローストーン川(ガーディナー)",
    nameEn: "Yellowstone River at Gardiner",
    category: "nature",
    handle: "SeeJH",
    channelId: "UCEpDjqeFIGTqHwk-uULx72Q",
    videoId: "IvZ22jZgvOI",
    titleKey: "Montana Whitewater - Yellowstone River in Gardiner",
    place: { name: "Gardiner", countryCode: "US", admin1: "Montana" },
  },
  {
    id: "grand-targhee",
    nameJa: "グランドターギー(アイダホ)",
    nameEn: "Grand Targhee Resort",
    category: "nature",
    handle: "SeeJH",
    channelId: "UCEpDjqeFIGTqHwk-uULx72Q",
    videoId: "fQiA_DZT0cE",
    titleKey: "Grand Targhee Resort Dreamcatcher - SeeJH.com",
    place: { name: "Driggs", countryCode: "US", admin1: "Idaho" },
  },

  // ── 鉄道 ───────────────────────────────────────────────
  {
    id: "rail-plant-city",
    nameJa: "プラントシティ(フロリダ)の線路",
    nameEn: "Plant City, Florida",
    category: "railway",
    handle: "VirtualRailfan",
    channelId: "UCOIkT9bq-1N2BvrsBjhNlag",
    videoId: "IVSoVgGXDoU",
    titleKey: "Plant City, Florida, USA | LIVE Train Camera (PTZ)",
    place: { name: "Plant City", countryCode: "US", admin1: "Florida" },
  },
  {
    id: "rail-folkston",
    nameJa: "フォルクストン(ジョージア)の線路",
    nameEn: "Folkston, Georgia",
    category: "railway",
    handle: "VirtualRailfan",
    channelId: "UCOIkT9bq-1N2BvrsBjhNlag",
    videoId: "7DmivRg6FfQ",
    titleKey: "Folkston, Georgia, USA | LIVE Train Camera (Turnout PTZ)",
    place: { name: "Folkston", countryCode: "US", admin1: "Georgia" },
  },
  {
    id: "rail-saint-louis",
    nameJa: "セントルイスの線路",
    nameEn: "Saint Louis, Missouri",
    category: "railway",
    handle: "VirtualRailfan",
    channelId: "UCOIkT9bq-1N2BvrsBjhNlag",
    videoId: "9eqVB3JbJHc",
    titleKey: "Saint Louis, Missouri, USA  |  LIVE Train Camera  (PTZ - West)",
    place: { name: "St. Louis", countryCode: "US", admin1: "Missouri" },
  },
  {
    id: "rail-cresson",
    nameJa: "クレッソン(ペンシルベニア)の線路",
    nameEn: "Cresson, Pennsylvania",
    category: "railway",
    handle: "VirtualRailfan",
    channelId: "UCOIkT9bq-1N2BvrsBjhNlag",
    videoId: "9uPCPh8jWas",
    titleKey: "Cresson, Pennsylvania  |  LIVE Train Camera (PTZ)",
    place: { name: "Cresson", countryCode: "US", admin1: "Pennsylvania" },
  },
  {
    id: "rail-salt-lake-city",
    nameJa: "ソルトレイクシティの線路",
    nameEn: "Salt Lake City, Utah",
    category: "railway",
    handle: "VirtualRailfan",
    channelId: "UCOIkT9bq-1N2BvrsBjhNlag",
    videoId: "qJd7diix4eI",
    titleKey: "Salt Lake City, Utah, USA | LIVE Train Camera (PTZ)",
    place: { name: "Salt Lake City", countryCode: "US", admin1: "Utah" },
  },
  {
    id: "rail-cheyenne",
    nameJa: "シャイアン(ワイオミング)の線路",
    nameEn: "Cheyenne, Wyoming",
    category: "railway",
    handle: "VirtualRailfan",
    channelId: "UCOIkT9bq-1N2BvrsBjhNlag",
    videoId: "hV30GxkdTAs",
    titleKey: "Cheyenne, Wyoming, USA  |  LIVE Train Camera (PTZ)",
    place: { name: "Cheyenne", countryCode: "US", admin1: "Wyoming" },
  },
  {
    id: "rail-quanah",
    nameJa: "クアナ(テキサス)の線路",
    nameEn: "Quanah, Texas",
    category: "railway",
    handle: "VirtualRailfan",
    channelId: "UCOIkT9bq-1N2BvrsBjhNlag",
    videoId: "LInPY_D1Ln4",
    titleKey: "Quanah, Texas, USA | LIVE Train Camera (PTZ)",
    place: { name: "Quanah", countryCode: "US", admin1: "Texas" },
  },
  {
    id: "rail-jesup",
    nameJa: "ジェサップ(ジョージア)の線路",
    nameEn: "Jesup, Georgia",
    category: "railway",
    handle: "VirtualRailfan",
    channelId: "UCOIkT9bq-1N2BvrsBjhNlag",
    videoId: "1AOrlYblQR8",
    titleKey: "Jesup, Georgia, USA | LIVE Train Camera | Virtual Railfan (PTZ)",
    place: { name: "Jesup", countryCode: "US", admin1: "Georgia" },
  },
  {
    id: "rail-seattle",
    nameJa: "シアトルの線路",
    nameEn: "Seattle, Washington",
    category: "railway",
    handle: "VirtualRailfan",
    channelId: "UCOIkT9bq-1N2BvrsBjhNlag",
    videoId: "pHqTDmH7H7c",
    titleKey: "Seattle, Washington, USA | LIVE Train Camera (PTZ)",
    place: { name: "Seattle", countryCode: "US", admin1: "Washington" },
  },
  {
    id: "rail-deshler",
    nameJa: "デシュラー(オハイオ)の線路",
    nameEn: "Deshler, Ohio",
    category: "railway",
    handle: "VirtualRailfan",
    channelId: "UCOIkT9bq-1N2BvrsBjhNlag",
    videoId: "TjMwpB8JRw8",
    titleKey: "Deshler, Ohio, USA | LIVE Train Camera (PTZ)",
    place: { name: "Deshler", countryCode: "US", admin1: "Ohio" },
  },
  {
    id: "rail-la-grange",
    nameJa: "ラグレンジ(ケンタッキー)の線路",
    nameEn: "La Grange, Kentucky",
    category: "railway",
    handle: "VirtualRailfan",
    channelId: "UCOIkT9bq-1N2BvrsBjhNlag",
    videoId: "OtssjZ3hdX0",
    titleKey: "La Grange, Kentucky, USA |  LIVE Railcam Camera (Observation Platform PTZ)",
    place: { name: "La Grange", countryCode: "US", admin1: "Kentucky" },
  },
  {
    id: "rail-tucson",
    nameJa: "ツーソン(アリゾナ)の線路",
    nameEn: "Tucson, Arizona",
    category: "railway",
    handle: "VirtualRailfan",
    channelId: "UCOIkT9bq-1N2BvrsBjhNlag",
    videoId: "q5BQRwSh41Q",
    titleKey: "Tucson, Arizona, USA | LIVE Train Camera (PTZ)",
    place: { name: "Tucson", countryCode: "US", admin1: "Arizona" },
  },
  {
    id: "rail-cumberland",
    nameJa: "カンバーランド(メリーランド)の線路",
    nameEn: "Cumberland, Maryland",
    category: "railway",
    handle: "VirtualRailfan",
    channelId: "UCOIkT9bq-1N2BvrsBjhNlag",
    videoId: "cR3kSHm7Ts0",
    titleKey: "CSX Mainline in Cumberland, Maryland, USA | LIVE Train Camera (PTZ – South)",
    place: { name: "Cumberland", countryCode: "US", admin1: "Maryland" },
  },
  {
    id: "rail-battle-creek",
    nameJa: "バトルクリーク(ミシガン)の線路",
    nameEn: "Battle Creek, Michigan",
    category: "railway",
    handle: "VirtualRailfan",
    channelId: "UCOIkT9bq-1N2BvrsBjhNlag",
    videoId: "m3iasBkPAbo",
    titleKey: "Battle Creek, Michigan, USA | LIVE Train Camera (PTZ)",
    place: { name: "Battle Creek", countryCode: "US", admin1: "Michigan" },
  },
  {
    id: "rail-ashland",
    nameJa: "アシュランド(バージニア)の線路",
    nameEn: "Ashland, Virginia",
    category: "railway",
    handle: "VirtualRailfan",
    channelId: "UCOIkT9bq-1N2BvrsBjhNlag",
    videoId: "_eArnSLGhSo",
    titleKey: "Ashland, Virginia, USA | LIVE Train Camera (PTZ)",
    place: { name: "Ashland", countryCode: "US", admin1: "Virginia" },
  },
  {
    id: "rail-cordele",
    nameJa: "コーデル(ジョージア)の線路",
    nameEn: "Cordele, Georgia",
    category: "railway",
    handle: "VirtualRailfan",
    channelId: "UCOIkT9bq-1N2BvrsBjhNlag",
    videoId: "ll3X1mH_g9Q",
    titleKey: "Cordele, Georgia, USA | LIVE Train Camera (Fixed View – Diamond)",
    place: { name: "Cordele", countryCode: "US", admin1: "Georgia" },
  },
  // ── 2 巡目に足したもの ─────────────────────────────────
  // 8 チャンネルに集中し米国に偏っていたので、豪州・アフリカ・火山を足した。
  // 候補 34 チャンネルを当たって、実際に「地理が定まるカメラ」を出していたのは
  // ここに挙げた 4 件だけだった(大半は報道の 24 時間配信でカメラではない)。
  {
    id: "sydney-harbour",
    nameJa: "シドニー湾（ハーバーブリッジとオペラハウス）",
    nameEn: "Sydney Harbour",
    category: "harbor",
    handle: "SydneyHarbourLive",
    channelId: "UCS03bU2sY5_zu2j7LoSjAVA",
    videoId: "VukSUsIGPGQ",
    titleKey: "Sydney Harbour LIVE 🇦🇺 Bridge & Opera House 24/7 — McMahons Point, Australia",
    at: { lat: -33.845, lng: 151.203, timeZone: "Australia/Sydney", country: "AU" },
  },
  {
    id: "kilauea-volcano",
    nameJa: "キラウエア火山（ハレマウマウ火口）",
    nameEn: "Kīlauea Volcano",
    category: "volcano",
    handle: "usgs",
    channelId: "UCeXH8GZyV3sVqAr45AvupOA",
    videoId: "HggWKlZv9yk",
    titleKey: "[V1cam] Kīlauea volcano, Hawaii (west Halemaʻumaʻu crater)",
    at: { lat: 19.4069, lng: -155.2834, timeZone: "Pacific/Honolulu", country: "US" },
  },
  {
    id: "rainbow-bridge",
    nameJa: "お台場・レインボーブリッジ",
    nameEn: "Rainbow Bridge, Tokyo",
    category: "city",
    handle: "FNNnewsCH",
    channelId: "UCoQBJMzcwmXrRSHBFAlTsIw",
    videoId: "kGG1CaeQ9oM",
    titleKey: "【ライブ】お台場・レインボーブリッジ - 首都高　ライブカメラ　Rainbow Bridge - Tokyo, Japan　 Live Cam",
    at: { lat: 35.636, lng: 139.7635, timeZone: "Asia/Tokyo", country: "JP" },
  },
  {
    id: "wildearth-safari",
    nameJa: "サビサンド動物保護区のサファリ中継",
    nameEn: "WildEarth Safari, Sabi Sand",
    category: "animal",
    handle: "WildEarth",
    channelId: "UCV6HJBZD_hZcIX9JVJ3dCXQ",
    videoId: "HRO9PwoduE8",
    titleKey: "WildEarth Channel - AD FREE",
    at: { lat: -24.79, lng: 31.45, timeZone: "Africa/Johannesburg", country: "ZA" },
  },
  // ── 3 巡目: キーワード検索で見つけた個人・自治体・施設のカメラ ────────
  // チャンネル起点だと、こちらが名前を知っている運営しか見つからない。
  // search.list を 8 語で回して 191 本の未知チャンネルを拾い、その中から
  // 「地理が一意に定まり、回転や巡回でない」ものを選んだ。
  {
    id: "osaka-dotonbori",
    nameJa: "大阪 道頓堀",
    nameEn: "Dotonbori, Osaka",
    category: "city",
    handle: "ラジカルビデオジョッキー RVJJP",
    channelId: "UCQ2mmGKtrBp6rL8tSMJCCwA",
    videoId: "i2PpmC1IeKk",
    titleKey: "【LIVE】大阪 道頓堀 ライブカメラ　osaka Dotonbori LiveCamera",
    at: { lat: 34.6687, lng: 135.5013, timeZone: "Asia/Tokyo", country: "JP" },
  },
  {
    id: "aso-nakadake",
    nameJa: "阿蘇中岳・草千里",
    nameEn: "Mount Aso",
    category: "volcano",
    handle: "自然公園財団 阿蘇支部",
    channelId: "UCey3hahtkbKG9VrXTSotZoQ",
    videoId: "-DDn7lAxR-8",
    titleKey: "阿蘇中岳・草千里 4Kライブカメラ / Aso Nakadake and Kusasenri 4K Live Camera",
    at: { lat: 32.8845, lng: 131.104, timeZone: "Asia/Tokyo", country: "JP" },
  },
  {
    id: "hakodate-station",
    nameJa: "函館駅前",
    nameEn: "Hakodate Station",
    category: "city",
    handle: "HAKODATE LIVE CAMERA",
    channelId: "UCynX4LJTQ_H7_KPy7QiIS2A",
    videoId: "rCgvMJGdhNo",
    titleKey: "【Live-Japan】函館駅前ライブカメラ② ※20秒ごとにアングルが変わります #JR函館駅 #函館 #路面電車 #HAKODATE",
    place: { name: "Hakodate", countryCode: "JP" },
  },
  {
    id: "naha-kokusai-dori",
    nameJa: "那覇 国際通り",
    nameEn: "Kokusai-dori, Naha",
    category: "city",
    handle: "バクノビジョン",
    channelId: "UCVg0E1H6LZBhTt_2oSm2Hzg",
    videoId: "D0hiHTAbu2A",
    titleKey: "【LIVE】沖縄ライブカメラ・那覇 国際通り /Okinawa Live Camera 24/7",
    place: { name: "Naha", countryCode: "JP" },
  },
  {
    id: "nagoya-station",
    nameJa: "名古屋駅",
    nameEn: "Nagoya Station",
    category: "city",
    handle: "鉄道沿線の生活",
    channelId: "UCjmqhsGQ9J1QK4r5mUrZb4A",
    videoId: "pI_u966ixNk",
    titleKey: "名古屋駅 ライブカメラ 愛知 鉄道 新幹線 天気 夜景 【4K配信】 Japan Nagoya Live Camera",
    place: { name: "Nagoya", countryCode: "JP" },
  },
  {
    id: "harajuku-station",
    nameJa: "原宿駅・表参道口",
    nameEn: "Harajuku Station",
    category: "city",
    handle: "原宿駅・表参道口 ライブカメラ [Harajuku Live Stream]",
    channelId: "UCpweG_uuLZhAH9B_Spwmmzg",
    videoId: "RUB0oL0SHl0",
    titleKey: "【4KLIVE】原宿駅前ライブカメラ｜表参道口・明治神宮 / Harajuku Live Stream (Omotesando, Meiji Jingu)",
    at: { lat: 35.6702, lng: 139.7027, timeZone: "Asia/Tokyo", country: "JP" },
  },
  {
    id: "yokohama-kishamichi",
    nameJa: "横浜 汽車道",
    nameEn: "Kishamichi, Yokohama",
    category: "harbor",
    handle: "横浜汽車道ライブカメラ /Live Cam Yokohama Japan",
    channelId: "UCKtFn0R-NGm6cocqdoGAQTA",
    videoId: "PEOE0ZpjdUg",
    titleKey: "🔴Live Cam Yokohama Japan :横浜汽車道ライブカメラ",
    at: { lat: 35.455, lng: 139.638, timeZone: "Asia/Tokyo", country: "JP" },
  },
  {
    id: "mount-fuji-kawaguchiko",
    nameJa: "富士山（河口湖）",
    nameEn: "Mount Fuji from Lake Kawaguchi",
    category: "nature",
    handle: "フジヤマNAVI",
    channelId: "UCwzJctz6m-0wG_evkheecZA",
    videoId: "Sv9hcJ3k5h4",
    titleKey: "【4K】富士山ライブカメラ / 4K Live Camera Mt.FUJI　～河口湖～富士山パノラマロープウェイ",
    at: { lat: 35.517, lng: 138.758, timeZone: "Asia/Tokyo", country: "JP" },
  },
  {
    id: "new-chitose-airport",
    nameJa: "新千歳空港",
    nameEn: "New Chitose Airport",
    category: "airport",
    handle: "HTB北海道テレビ",
    channelId: "UCuY1i-Tic2G2xmox2_0h-Fw",
    videoId: "Azbdr5jbN6o",
    titleKey: "【LIVE】いまの新千歳空港／Live streaming from Hokkaido　 New Chitose Airport　北海道ｏｎ天気カメラ",
    place: { name: "Chitose", countryCode: "JP" },
  },
  {
    id: "narita-airport",
    nameJa: "成田空港",
    nameEn: "Narita Airport",
    category: "airport",
    handle: "朝日新聞LIVE",
    channelId: "UCaHr0a1x8zmQ1dxanCeuesA",
    videoId: "OuCbntsMsWY",
    titleKey: "【LIVE】成田空港ライブカメラ　A滑走路(南側）＠朝日新聞成田支局  LIVE at Narita International airport",
    at: { lat: 35.7647, lng: 140.3864, timeZone: "Asia/Tokyo", country: "JP" },
  },
  {
    id: "itami-airport",
    nameJa: "大阪 伊丹空港",
    nameEn: "Itami Airport",
    category: "airport",
    handle: "MBS NEWS",
    channelId: "UCkKJhKO73xF1pK5h9R82ZGQ",
    videoId: "GwxeN9lQhnM",
    titleKey: "【LIVE】大阪・伊丹空港のライブカメラ 　飛行機の離着陸や空港の様子は？ OSAKA  Itami Airport【生配信】",
    at: { lat: 34.7855, lng: 135.4382, timeZone: "Asia/Tokyo", country: "JP" },
  },
  {
    id: "satsukiyama-wombat",
    nameJa: "五月山動物園のウォンバット",
    nameEn: "Satsukiyama Zoo Wombats",
    category: "animal",
    handle: "【公式】五月山動物園 ウォンバットてれび",
    channelId: "UC3fDjbb2JVIX6rOLNNqctow",
    videoId: "m0zx7vPJtC0",
    titleKey: "Satsukiyama DAYZOO　ウォンバットライブカメラ　～世界で唯一のウォンバットのライブ映像をお届け～",
    place: { name: "Ikeda", countryCode: "JP" },
  },
  {
    id: "shonan-kugenuma",
    nameJa: "湘南 鵠沼海岸",
    nameEn: "Kugenuma Beach, Shonan",
    category: "nature",
    handle: "NAMIARUMOVIE",
    channelId: "UCV3arNLjYmBubfETmAAzS4w",
    videoId: "DZWA9Xicaxg",
    titleKey: "湘南 鵠沼〜新江ノ島水族館前　ライブ配信",
    at: { lat: 35.313, lng: 139.477, timeZone: "Asia/Tokyo", country: "JP" },
  },
  {
    id: "venice-rolling",
    nameJa: "ヴェネツィア",
    nameEn: "Venice",
    category: "city",
    handle: "I Love You Venice",
    channelId: "UCMpn1qLudF-zb4M4bqxLIbw",
    videoId: "a1mcaV3Sf9U",
    titleKey: "🔴 LIVE 24/7  Rolling Cam Venice - Live Cam in Venice Italy - Livecam en direct #venice",
    at: { lat: 45.4341, lng: 12.3388, timeZone: "Europe/Rome", country: "IT" },
  },
  {
    id: "lourdes-sanctuary",
    nameJa: "ルルドの聖域",
    nameEn: "Sanctuary of Lourdes",
    category: "city",
    handle: "Sanctuaire Notre-Dame de Lourdes",
    channelId: "UC7zlbnNCnuAPiC3goKcFgUg",
    videoId: "ESNa1vdHcYY",
    titleKey: "🔴Lourdes+ | Le Sanctuaire Notre-Dame de Lourdes en direct.",
    place: { name: "Lourdes", countryCode: "FR" },
  },
  {
    id: "hamburg-harbour",
    nameJa: "ハンブルク港",
    nameEn: "Hamburg Harbour",
    category: "harbor",
    handle: "livespotting",
    channelId: "UCzLB2h38nyHSIaALzwtPvfg",
    videoId: "OmyDLXvaus4",
    titleKey: "🔴 LIVE: Hamburg Michel – Webcam mit Panoramablick auf Hafen",
    place: { name: "Hamburg", countryCode: "DE" },
  },
  {
    id: "gottingen-market",
    nameJa: "ゲッティンゲン 市庁舎前広場",
    nameEn: "Göttingen Market Square",
    category: "city",
    handle: "GöCam",
    channelId: "UCFu4lC8Wlq4fOLpW3zf_4wg",
    videoId: "cfCKCrOyHmw",
    titleKey: "LIVE Webcam Germany: Göttingen - Historisches Rathaus und Gänseliesel-Brunnen",
    place: { name: "G\u00f6ttingen", countryCode: "DE" },
  },
  {
    id: "rees-rhine",
    nameJa: "ライン川（レース）",
    nameEn: "River Rhine at Rees",
    category: "nature",
    handle: "Stadt Rees",
    channelId: "UCaLDNGnkbTjnpG7j00om-Qg",
    videoId: "SeN3fw3R6-E",
    titleKey: "Live Rhein bei Rees, rheinabwärts Richtung Emmerich",
    place: { name: "Rees", countryCode: "DE" },
  },
  {
    id: "st-ives-harbour",
    nameJa: "セント・アイヴス港",
    nameEn: "St Ives Harbour",
    category: "harbor",
    handle: "Aspects Holidays",
    channelId: "UC683QcyNqiaLGAB3OidWtBw",
    videoId: "T83mKGf_c3k",
    titleKey: "Live webcam of St Ives Harbour in Cornwall, UK.",
    place: { name: "St Ives", countryCode: "GB", admin1: "England" },
  },
  {
    id: "dublin-port",
    nameJa: "ダブリン港",
    nameEn: "Dublin Port",
    category: "harbor",
    handle: "Dublin Port",
    channelId: "UCeGyo_v1ppwH-e77CVqLSJg",
    videoId: "oxx7MqjhOpw",
    titleKey: "Dublin Bay Live: Watch Ships Enter and Exit Dublin Port",
    place: { name: "Dublin", countryCode: "IE" },
  },
  {
    id: "helsinki-port",
    nameJa: "ヘルシンキ港",
    nameEn: "Port of Helsinki",
    category: "harbor",
    handle: "Port of Helsinki",
    channelId: "UCuaFFNhZkcEg2JjEPvzjzzw",
    videoId: "JnJhFYhIjFs",
    titleKey: "Port of Helsinki - West harbour - north cam",
    place: { name: "Helsinki", countryCode: "FI" },
  },
  {
    id: "geirangerfjord",
    nameJa: "ガイランゲルフィヨルド",
    nameEn: "Geirangerfjord",
    category: "nature",
    handle: "Geirangerfjord cruise port",
    channelId: "UCbYNIUYxdzeQTKdb9GfJl3w",
    videoId: "yMSc-qqW3To",
    titleKey: "Geirangerfjord cruise port, Geiranger",
    place: { name: "Geiranger", countryCode: "NO" },
  },
  {
    id: "hvar",
    nameJa: "フヴァル島（クロアチア）",
    nameEn: "Hvar, Croatia",
    category: "city",
    handle: "Hvar Live",
    channelId: "UCQmlVF-VRx75AflM-9gJytg",
    videoId: "0wHWHAFnNh0",
    titleKey: "Hvar, Croatia ☀ LIVE 24/7 WebCam",
    place: { name: "Hvar", countryCode: "HR" },
  },
  {
    id: "benidorm",
    nameJa: "ベニドルム海岸",
    nameEn: "Benidorm Beach",
    category: "nature",
    handle: "BeniCam - Benidorm Webcam",
    channelId: "UCVlxVWLL0C1U9HRe9Nt55Lw",
    videoId: "M-2LWrTyPnY",
    titleKey: "BENIDORM LIVE WEBCAM 🇪🇸 🔴 LIVE: Spain Resort Beach Twilight Real-Time 🌅🌊🏖️",
    place: { name: "Benidorm", countryCode: "ES" },
  },
  {
    id: "lanzarote-airport",
    nameJa: "ランサローテ空港",
    nameEn: "Lanzarote Airport",
    category: "airport",
    handle: "LanzaroteWebcam",
    channelId: "UCUaLy1_4rsLo4HyCLCPlD4g",
    videoId: "AAlo3eCPVbk",
    titleKey: "LIVE 🔴 WEBCAM from LANZAROTE AIRPORT - (Canary Islands, Spain)",
    place: { name: "Arrecife", countryCode: "ES" },
  },
  {
    id: "portsmouth-hms-warrior",
    nameJa: "ポーツマス HMSウォーリア",
    nameEn: "HMS Warrior, Portsmouth",
    category: "harbor",
    handle: "Royal Navy Museums",
    channelId: "UC3ppRbUdj-XrSIn-6YHGP3w",
    videoId: "N9KCrI_-Zv0",
    titleKey: "HMS Warrior Webcam",
    place: { name: "Portsmouth", countryCode: "GB", admin1: "England" },
  },
  {
    id: "rutland-osprey",
    nameJa: "ラトランドのミサゴ",
    nameEn: "Rutland Ospreys",
    category: "animal",
    handle: "Rutland Osprey Project",
    channelId: "UCJ8DHJ5VCVLm-o_Wo65VBaA",
    videoId: "CKvLj6ZFNcA",
    titleKey: "LRWT - Manton Bay Ospreys Live Webcam (Close-up)",
    place: { name: "Oakham", countryCode: "GB", admin1: "England" },
  },
  {
    id: "bad-salzungen-stork",
    nameJa: "バート・ザルツンゲンのコウノトリ",
    nameEn: "Stork Nest, Bad Salzungen",
    category: "animal",
    handle: "Stadtverwaltung Bad Salzungen",
    channelId: "UCzAuBgdr5YC8ARNRMWgIAXg",
    videoId: "Dr5zebXpO-M",
    titleKey: "Storchennest Live Webcam in Bad Salzungen, Thüringen",
    place: { name: "Bad Salzungen", countryCode: "DE" },
  },
  {
    id: "chengdu-panda",
    nameJa: "成都 ジャイアントパンダ基地",
    nameEn: "Chengdu Panda Base",
    category: "animal",
    handle: "iPanda",
    channelId: "UCtEgLf0_j1vJLz0aNEdO2SQ",
    videoId: "SUXPnIEpbn4",
    titleKey: "Panda 24/7 HD Live At Chengdu Panda Base",
    place: { name: "Chengdu", countryCode: "CN" },
  },
  {
    id: "taoyuan-airport",
    nameJa: "桃園国際空港",
    nameEn: "Taoyuan International Airport",
    category: "airport",
    handle: "Taoyuan Airport",
    channelId: "UC8nqJIBj9B4DimyFEtQ6RpA",
    videoId: "wWEnxWA7nnY",
    titleKey: "🔴 TPE 4K桃園國際機場 北跑道觀景台即時影像｜Taoyuan International Airport North Runway Live plane spotting",
    place: { name: "Taoyuan", countryCode: "TW" },
  },
  {
    id: "alishan",
    nameJa: "阿里山（奮起湖）",
    nameEn: "Alishan, Taiwan",
    category: "nature",
    handle: "阿里山國家風景區管理處",
    channelId: "UCQqyZgPh9Lu0w_rmWWBvuNg",
    videoId: "B6eki-0-w0g",
    titleKey: "4K Live cam-Alishan【阿里山美景4K直播】-奮起湖 Fenqihu",
    // ジオコーダは「阿里山」を嘉義市(約 25km 西)に解決してしまうので、
    // 配信地点である奮起湖の座標を明示する。
    at: { lat: 23.5085, lng: 120.6975, timeZone: "Asia/Taipei", country: "TW" },
  },
  {
    id: "hongkong-aberdeen",
    nameJa: "香港 アバディーン港",
    nameEn: "Aberdeen Harbour, Hong Kong",
    category: "harbor",
    handle: "香港人の日常生活",
    channelId: "UCBDx32JFg9vk9VHtQppv5tg",
    videoId: "DkmX5xQer1c",
    titleKey: "24/7 HK Live - Hong Kong Aberdeen Harbour Live Camera - 香港市景即時影像 香港仔海峽",
    at: { lat: 22.247, lng: 114.155, timeZone: "Asia/Hong_Kong", country: "HK" },
  },
  {
    id: "koh-samui",
    nameJa: "サムイ島 ラマイビーチ",
    nameEn: "Lamai Beach, Koh Samui",
    category: "nature",
    handle: "The Real Samui Webcam",
    channelId: "UCmYyJaUxYiF5IbLx-0jFXHQ",
    videoId: "kkVrj2cr9Ko",
    titleKey: "🔴 LIVE Crystal Bay Yacht Club Lamai | Koh Samui Beach Webcam | Thailand 24/7 | 1080p HD",
    place: { name: "Ko Samui", countryCode: "TH" },
  },
  {
    id: "everest-view",
    nameJa: "エベレスト・ビュー（ネパール）",
    nameEn: "Hotel Everest View, Nepal",
    category: "nature",
    handle: "WEBCAM NEPAL LIVE",
    channelId: "UCCCVkU6r9ZTD8E4z7AtuOIw",
    videoId: "SXsPeIqGJMA",
    titleKey: "WEBCAM NEPAL LIVE – PANORAMIC VIEWS FROM HOTEL EVEREST VIEW - NOW WITH LIVE AUDIO!",
    place: { name: "Namche Bazar", countryCode: "NP" },
  },
  {
    id: "davao-market",
    nameJa: "ダバオ アグダオ市場",
    nameEn: "Agdao Market, Davao",
    category: "city",
    handle: "Edge Babor Family PH ",
    channelId: "UCa6T92S2NKwSdQw8rXLe2rQ",
    videoId: "u8CbGedbI08",
    titleKey: "🔴 LIVE: Agdao Market, Davao City Philippines|Real-Time CCTV|EdgeBabor Philippines",
    place: { name: "Davao", countryCode: "PH" },
  },
  {
    id: "auckland-harbour",
    nameJa: "オークランド港",
    nameEn: "Auckland Harbour",
    category: "harbor",
    handle: "Auckland City Views",
    channelId: "UCnuF5fiEc6DdbhDHCQoCAfA",
    videoId: "PaLDpyFxpXE",
    titleKey: "🔴 LIVE Auckland NOW 🌤️ Harbour, Skyline &amp; Cruise Ships | 4K 24/7 #livecam",
    place: { name: "Auckland", countryCode: "NZ" },
  },
  {
    id: "newcastle-port",
    nameJa: "ニューカッスル港（豪）",
    nameEn: "Port of Newcastle",
    category: "harbor",
    handle: "Port of Newcastle",
    channelId: "UCTGhjtFloAPlbLy4_yrkoWg",
    videoId: "dypAtzvl24s",
    titleKey: "Port of Newcastle Harbour Cam",
    place: { name: "Newcastle", countryCode: "AU", admin1: "New South Wales" },
  },
  {
    id: "rio-copacabana",
    nameJa: "リオ コパカバーナ海岸",
    nameEn: "Copacabana, Rio de Janeiro",
    category: "nature",
    handle: "Homes in Rio",
    channelId: "UChWGYkK0I8U83C0FxAxWy4w",
    videoId: "65lUphjTAro",
    titleKey: "Webcam Rio de Janeiro Copacabana Posto 6",
    at: { lat: -22.9711, lng: -43.1822, timeZone: "America/Sao_Paulo", country: "BR" },
  },
  {
    id: "buenos-aires-uade",
    nameJa: "ブエノスアイレス",
    nameEn: "Buenos Aires",
    category: "city",
    handle: "UADE",
    channelId: "UCJbgNz5VfETvD_wd4KiF2yQ",
    videoId: "NfsyRx50gAI",
    titleKey: "Cámara en vivo | UADE Campus Buenos Aires",
    place: { name: "Buenos Aires", countryCode: "AR" },
  },
  {
    id: "montreal-airport",
    nameJa: "モントリオール空港",
    nameEn: "Montréal–Trudeau Airport",
    category: "airport",
    handle: "Moore Equipment Ltd.",
    channelId: "UCmM8fJ5uDl8pqu8nnd8Ixlg",
    videoId: "iJxeutc3QCI",
    titleKey: "LIVE Montreal Trudeau Airport CYUL 24/7 Webcam Runway 24L",
    place: { name: "Montreal", countryCode: "CA" },
  },
  {
    id: "vancouver-harbour",
    nameJa: "バンクーバー港",
    nameEn: "Vancouver Harbour",
    category: "harbor",
    handle: "Vancouver City Views",
    channelId: "UCYky246qWfKe82NLQ9VXbgQ",
    videoId: "rxyNjFKwzJA",
    titleKey: "🔴🚢 Vancouver LIVE Cam | Cruise Ship LiveStream 24/7 | City Views &amp; Canada Place | Alaska Season 2026",
    place: { name: "Vancouver", countryCode: "CA", admin1: "British Columbia" },
  },
  {
    id: "maho-beach",
    nameJa: "マホビーチ（着陸機が頭上を通る）",
    nameEn: "Maho Beach, St Maarten",
    category: "airport",
    handle: "SHOWME Caribbean",
    channelId: "UCRjMuOBDCfSsCNIe2p0_tdg",
    videoId: "iSeH45R-8R0",
    titleKey: "✈️  Maho Beach Saint Martin | Princess Juliana Airport Beach 24/7 | LIVE Cam",
    place: { name: "Philipsburg", countryCode: "SX" },
  },
  {
    id: "mount-st-helens",
    nameJa: "セント・ヘレンズ山",
    nameEn: "Mount St. Helens",
    category: "volcano",
    handle: "Mount St. Helens Institute",
    channelId: "UC21fnDewX_begL0xw8U3ljg",
    videoId: "YTZe2eyO824",
    titleKey: "**LIVE** Mount St. Helens | Coldwater Lake Weather Cam",
    place: { name: "Toutle", countryCode: "US", admin1: "Washington" },
  },
  {
    id: "brooks-falls",
    nameJa: "ブルックス滝のヒグマ",
    nameEn: "Brooks Falls Bears, Katmai",
    category: "animal",
    handle: "Explore Live Nature Cams",
    channelId: "UC-2KSeUU5SMCX6XLRD-AEvw",
    videoId: "J7ZrIDvqlic",
    titleKey: "LIVE Brooks Falls - Katmai National Park, Alaska 2026 | explore.org",
    place: { name: "King Salmon", countryCode: "US", admin1: "Alaska" },
  },
  {
    id: "big-bear-eagle",
    nameJa: "ビッグベアのハクトウワシ",
    nameEn: "Big Bear Bald Eagles",
    category: "animal",
    handle: "FOBBV CAM",
    channelId: "UCsFgbVuhRrPV5FqyN7kOD8g",
    videoId: "41eq4VzCYc4",
    titleKey: "Big Bear Bald Eagle Wide View - Cam 2",
    place: { name: "Big Bear Lake", countryCode: "US", admin1: "California" },
  },
  {
    id: "mount-washington",
    nameJa: "ワシントン山観測所",
    nameEn: "Mount Washington Observatory",
    category: "nature",
    handle: "Mount Washington Observatory",
    channelId: "UCq-cqqXchflIRPLsf_n3wlg",
    videoId: "Z27ghRYocJ4",
    titleKey: "LIVE: Mount Washington Observatory Deck Cam",
    place: { name: "Gorham", countryCode: "US", admin1: "New Hampshire" },
  },
  {
    id: "waikiki-beach",
    nameJa: "ワイキキビーチ",
    nameEn: "Waikiki Beach",
    category: "nature",
    handle: "Ozolio Plus",
    channelId: "UCspnu6n44ydqafj6nFIw5hw",
    videoId: "U_Jsbq9kYE8",
    titleKey: "Park Shore Waikiki Hotel Live Cam | Waikiki Beach, Honolulu",
    place: { name: "Honolulu", countryCode: "US", admin1: "Hawaii" },
  },
  {
    id: "lax-airport",
    nameJa: "ロサンゼルス国際空港",
    nameEn: "Los Angeles International Airport",
    category: "airport",
    handle: "AirlineVideosLive+",
    channelId: "UCox5yCEEjk4iYbhLgyj90EQ",
    videoId: "n4I0d44oBEs",
    titleKey: "🔴LIVE 24/7 LAX Airport Action Runways 24L &amp; 24R | LIVE Plane Spotting with ATC!",
    place: { name: "Los Angeles", countryCode: "US", admin1: "California" },
  },
  // ── 4 巡目: 言語と regionCode を振った検索 ────────────────
  // 3 巡目は英語と日本語の語だけだったので、結果が英語圏に寄っていた。
  // ポルトガル語・スペイン語・韓国語・中国語・ポーランド語・トルコ語などで
  // 掘り直し、アフリカ・韓国・台湾・南米・東欧を足した。
  {
    id: "maasai-mara",
    nameJa: "マサイマラ国立保護区",
    nameEn: "Maasai Mara, Kenya",
    category: "animal",
    handle: "SBC-TV | Maasai Mara Live Safari",
    channelId: "UCv7WvXfp-l07Z6IuComA36w",
    videoId: "gVNpA3WNMyc",
    titleKey: "🔴 LIVE African Safari | 6 Maasai Mara Wildlife Cameras | Kenya 24/7",
    at: { lat: -1.4833, lng: 35.15, timeZone: "Africa/Nairobi", country: "KE" },
  },
  {
    id: "etosha-okaukuejo",
    nameJa: "エトーシャ国立公園の水場",
    nameEn: "Etosha Waterhole, Namibia",
    category: "animal",
    handle: "Namibia Wildlife Resorts",
    channelId: "UCfn4vrrgKXCCg3rxxLRGOvg",
    videoId: "JMMoRwYo5kE",
    titleKey: "Okaukuejo Resort, Wildlife Waterhole: Live camera stream in the Etosha National Park in Namibia",
    at: { lat: -19.1817, lng: 15.9128, timeZone: "Africa/Windhoek", country: "NA" },
  },
  {
    id: "stony-point-penguins",
    nameJa: "ストーニーポイントのペンギン",
    nameEn: "African Penguins, Stony Point",
    category: "animal",
    handle: "Africam Conservation",
    channelId: "UCgWh6X0Yop6k7X6ShWIBVsg",
    videoId: "NiwrvhQIHIo",
    titleKey: "Watch African Penguins LIVE | Stony Point Colony | South Africa",
    // ジオコーダに Betty's Bay の登録が無いので、ペンギンのコロニーがある
    // ストーニーポイント自然保護区の座標を明示する。
    at: { lat: -34.3733, lng: 18.8925, timeZone: "Africa/Johannesburg", country: "ZA" },
  },
  {
    id: "hoedspruit-rhino",
    nameJa: "ホードスプロイトのサイ",
    nameEn: "Rhino Cam, Hoedspruit",
    category: "animal",
    handle: "Explore African Wildlife",
    channelId: "UCMfjW-9aZnsR-Rq-Ngo4CpQ",
    videoId: "wtylzrJvCKU",
    titleKey: "LIVE Africam Rhino Cam at the Hoedspruit Endangered Species Centre - South Africa | explore.org",
    place: { name: "Hoedspruit", countryCode: "ZA" },
  },
  {
    id: "busan-haeundae",
    nameJa: "釜山 海雲台ビーチ",
    nameEn: "Haeundae Beach, Busan",
    category: "nature",
    handle: "Busan Haeundae Live [부산 해운대 라이브]",
    channelId: "UCZsIhpfgnO7nNrDWu7dj89g",
    videoId: "LGuktGeHQxI",
    titleKey: "[실시간 해운대해수욕장] 4K Live Cam Haeundae Busan, Transmisión en vivo de la cámara de Haeundae",
    place: { name: "Busan", countryCode: "KR" },
  },
  {
    id: "jeju-seongsan",
    nameJa: "済州島 城山",
    nameEn: "Seongsan, Jeju Island",
    category: "nature",
    handle: "펀제주",
    channelId: "UC-cGXwzS7XwlVn6zaPa3CDw",
    videoId: "NCzm0l_ZqzU",
    titleKey: "펀제주 제주도 서귀포 성산읍 지금 날씨 실시간 제주 오늘 라이브 캠,   Jeju Island in South Korea Live CCTV Cam Sungsanilchulbong",
    place: { name: "Seogwipo", countryCode: "KR" },
  },
  {
    id: "seoul-seongsu",
    nameJa: "ソウル 聖水洞",
    nameEn: "Seongsu, Seoul",
    category: "city",
    handle: "성수라이브",
    channelId: "UCNdb9Zrjyn_6Ot_91JdRXlw",
    videoId: "vUd4w805yNU",
    titleKey: "성수 핫플 라이브(Seoul Korea Seongsu Station Live Cam)",
    place: { name: "Seoul", countryCode: "KR" },
  },
  {
    id: "daejeon-expo",
    nameJa: "大田 エキスポ科学公園",
    nameEn: "Expo Science Park, Daejeon",
    category: "city",
    handle: "GiGAeyes Live TV",
    channelId: "UCsy6UOjk8q7Ajq9yQ7iDAbA",
    videoId: "CQO1Ka7HqCg",
    titleKey: "대전실시간 대전라이브 대전엑스포과학공원 한빛광장 LiveCam I &quot;ExpoSciencePark,Hanbit Square&quot;,Daejeon,Korea I 대전관광공사 대전여행",
    place: { name: "Daejeon", countryCode: "KR" },
  },
  {
    id: "jiufen",
    nameJa: "九份",
    nameEn: "Jiufen, Taiwan",
    category: "city",
    handle: "新北旅客 New Taipei Tour",
    channelId: "UCm8_3Nf9LFmPwuKSvYhhwLw",
    videoId: "XSD5ptYisw8",
    titleKey: "九份即時影像 Jiufen Live Camera 실시간 주펀 라이브캠  | 新北觀光即時影像 | ライブカメラ",
    place: { name: "Jiufen", countryCode: "TW" },
  },
  {
    id: "taipei-xiangshan",
    nameJa: "台北 象山からの眺め",
    nameEn: "Taipei from Xiangshan",
    category: "city",
    handle: "Taipei Travel Live Cam  台北觀光即時影像 ",
    channelId: "UCJLjpq7pTJRbP3vtx0LxB9Q",
    videoId: "z_fY1pj1VBw",
    titleKey: "【Taipei Live Cam】象山看台北 - 4K即時影像 | Overlooking Taipei at the top of Xiangshan | 象山から望む台北 | Taipei 101",
    place: { name: "Taipei", countryCode: "TW" },
  },
  {
    id: "duoliang-station",
    nameJa: "台東 多良駅",
    nameEn: "Duoliang Station, Taitung",
    category: "railway",
    handle: "Amazing Taitung 台東就醬玩",
    channelId: "UCT4jEYvUdpdN9oUALaypGfQ",
    videoId: "UCG1aXVO8H8",
    titleKey: "【4K】台東多良車站即時影像 Taitung Duoliang Station Live Camera",
    at: { lat: 22.423, lng: 120.888, timeZone: "Asia/Taipei", country: "TW" },
  },
  {
    id: "assisi-basilica",
    nameJa: "アッシジ 聖フランチェスコ聖堂",
    nameEn: "Basilica of San Francesco, Assisi",
    category: "city",
    handle: "Umbria Webcam",
    channelId: "UC_FuR9GFVJE2A8H02sQmHWw",
    videoId: "5ka3YhVZgME",
    titleKey: "🔴Assisi Live Webcam Basilica di San Francesco",
    place: { name: "Assisi", countryCode: "IT" },
  },
  {
    id: "mount-etna",
    nameJa: "エトナ火山",
    nameEn: "Mount Etna",
    category: "volcano",
    handle: "Vincenzo Modica",
    channelId: "UC_LnSAP1K6UmVEVT1mGy_AQ",
    videoId: "t4vlFU-ypIw",
    titleKey: "🔴 Mount Etna Live Stream – Real-Time Volcano Webcam (Sicily, Italy) | 18 August 2026",
    at: { lat: 37.751, lng: 14.9934, timeZone: "Europe/Rome", country: "IT" },
  },
  {
    id: "dresden-elbe",
    nameJa: "ドレスデン エルベ川",
    nameEn: "Elbe at Dresden",
    category: "city",
    handle: "viewatch.tv",
    channelId: "UCOl2i5KaGd2y_0CbSeS7TBA",
    videoId: "vTJGeIvg8EY",
    titleKey: "Livecam Elbufer Dresden / Live from the river Elbe &amp; Panorama of Dresden",
    place: { name: "Dresden", countryCode: "DE" },
  },
  {
    id: "berlin-webcam",
    nameJa: "ベルリン",
    nameEn: "Berlin",
    category: "city",
    handle: "Günther Kohlbecker",
    channelId: "UCpR-vq358IEHwt-FgPsEBpA",
    videoId: "4Xg-wkPazp4",
    titleKey: "BerlinWebcam1",
    place: { name: "Berlin", countryCode: "DE" },
  },
  {
    id: "hannover-railway",
    nameJa: "ハノーファーの線路",
    nameEn: "Hannover Railway",
    category: "railway",
    handle: "Railcam Hannover",
    channelId: "UCKUb0TwifX_aQODQosDAfoA",
    videoId: "0i1ZP_oc86w",
    titleKey: "LIVE: Train Traffic in Hannover Germany | ICEs, REs, Freight Trains | 24/7 Live Stream",
    place: { name: "Hannover", countryCode: "DE" },
  },
  {
    id: "jasna-gora",
    nameJa: "ヤスナ・グラ修道院",
    nameEn: "Jasna Góra Monastery",
    category: "city",
    handle: "Jasna Góra Klasztor Ojców Paulinów",
    channelId: "UCKAtPxfE2RAHSCwDABMMeAg",
    videoId: "yMxD3gdeXmk",
    titleKey: "Jasna Góra Klasztor Ojców Paulinów – transmisja na żywo, ON-LINE, msza święta na żywo",
    place: { name: "Czestochowa", countryCode: "PL" },
  },
  {
    id: "scheveningen",
    nameJa: "スヘフェニンゲン海岸",
    nameEn: "Scheveningen Beach",
    category: "nature",
    handle: "Strandweer.nu",
    channelId: "UCgDKPUQWlxzaqPm6tOFrInw",
    videoId: "A5kXiKzbBFs",
    titleKey: "Live Scheveningen Boulevard en Beach Camera",
    place: { name: "Scheveningen", countryCode: "NL" },
  },
  {
    id: "amsterdam-bridges",
    nameJa: "アムステルダム 五つの橋",
    nameEn: "De Vijf Bruggen, Amsterdam",
    category: "railway",
    handle: "ProRail",
    channelId: "UCn4oQ60oxfvq7aesEPYqpKw",
    videoId: "2tgHBRFHMm8",
    titleKey: "Amsterdam De Vijf Bruggen camera 1",
    place: { name: "Amsterdam", countryCode: "NL" },
  },
  {
    id: "hastings-pier",
    nameJa: "ヘイスティングズ桟橋",
    nameEn: "Hastings Pier",
    category: "harbor",
    handle: "Beaming",
    channelId: "UCBHhwpHuJR4ZSH8gvxT0DdQ",
    videoId: "5FBMg0K85Jg",
    titleKey: "Hastings Pier Webcam and English Channel LIVE HD",
    place: { name: "Hastings", countryCode: "GB", admin1: "England" },
  },
  {
    id: "st-petersburg-nevsky",
    nameJa: "サンクトペテルブルク ネフスキー大通り",
    nameEn: "Nevsky Prospect, St Petersburg",
    category: "city",
    handle: "Mobotix Webcams Russia | Marathon to 100k",
    channelId: "UCz1GKiqSoG2DSesCQ3SoFYg",
    videoId: "fUsJZTHeZn4",
    titleKey: "LIVE Nevskiy avenue St. Petersburg Russia Anichkov Palace Невский пр. Аничков дворец Санкт-Петербург",
    place: { name: "Saint Petersburg", countryCode: "RU" },
  },
  {
    id: "sagvar-stork",
    nameJa: "シャーグヴァールのコウノトリ",
    nameEn: "Stork Nest, Ságvár",
    category: "animal",
    handle: "Madarles - Live Bird Cams",
    channelId: "UCU31-9qcY1RDuMad67dbuhw",
    videoId: "AO5I5nNbbnE",
    titleKey: "LIVE White Stork Nest Cam (Ságvár, Hungary)",
    place: { name: "Sagvar", countryCode: "HU" },
  },
  {
    id: "rio-christ-redeemer",
    nameJa: "リオ コルコバードのキリスト像",
    nameEn: "Christ the Redeemer, Rio",
    category: "city",
    handle: "Live Rio",
    channelId: "UCfMOswhx9NN_laZ8Ukcm4-Q",
    videoId: "PhYE9txaPlo",
    titleKey: "Cristo Redentor Ao Vivo En Vivo| Christ the Redeemer Live Cam — Rio de Janeiro Brazil",
    at: { lat: -22.9519, lng: -43.2105, timeZone: "America/Sao_Paulo", country: "BR" },
  },
  {
    id: "balneario-camboriu",
    nameJa: "バルネアリオ・カンボリウ",
    nameEn: "Balneário Camboriú",
    category: "nature",
    handle: "CLIMA BC Brazil",
    channelId: "UCi1vQx48j_nfrMg6XH5PItQ",
    videoId: "5Xl6pSgiy3A",
    titleKey: "Balneário Camboriú ao vivo - Avenida Atlântica",
    place: { name: "Balneario Camboriu", countryCode: "BR" },
  },
  {
    id: "natal-ponta-negra",
    nameJa: "ナタール ポンタネグラ海岸",
    nameEn: "Ponta Negra, Natal",
    category: "nature",
    handle: "Live Cam Natal",
    channelId: "UC-dGHuK8OcC_WIWvNzxysag",
    videoId: "TxzuYLK_ZXo",
    titleKey: "PRAIA DE PONTA NEGRA AO VIVO! NATAL-RN / BRASIL - LIVE CAM NATAL",
    place: { name: "Natal", countryCode: "BR", admin1: "Rio Grande do Norte" },
  },
  {
    id: "manaus-ponta-negra",
    nameJa: "マナウス ポンタネグラ",
    nameEn: "Ponta Negra, Manaus",
    category: "nature",
    handle: "AmzLive",
    channelId: "UCH9JbKmqTI6gwhA4ghl32FQ",
    videoId: "xt5k4nWXOEc",
    titleKey: "Ponta Negra ao Vivo 24h - Manaus - AmzLive.com.br",
    place: { name: "Manaus", countryCode: "BR" },
  },
  {
    id: "concepcion-chile",
    nameJa: "コンセプシオン（チリ）",
    nameEn: "Concepción, Chile",
    category: "city",
    handle: "ConceCam",
    channelId: "UCJizf5PzUJ88hro1m-cUcSA",
    videoId: "RhdmP5017VM",
    titleKey: "CONCECAM - Concepción Centro, Chile - Cámara Ultra HD en vivo y en directo, live cam",
    place: { name: "Concepcion", countryCode: "CL" },
  },
  {
    id: "valparaiso",
    nameJa: "バルパライソ（チリ）",
    nameEn: "Valparaíso, Chile",
    category: "harbor",
    handle: "Manupuntocl",
    channelId: "UCXaQjESu5cdF1CGH1aAA52Q",
    videoId: "5jPpMkg5daM",
    titleKey: "Valparaíso, Chile EN VIVO | LIVE CAM",
    place: { name: "Valparaiso", countryCode: "CL" },
  },
  {
    id: "porto-alegre-airport",
    nameJa: "ポルトアレグレ空港",
    nameEn: "Porto Alegre Airport",
    category: "airport",
    handle: "Camera Aeroporto Porto Alegre BrAmigos",
    channelId: "UCFGIPvN1dMn4Bdo8B8WWPDw",
    videoId: "IdAvz5TD6Wc",
    titleKey: "SBPA / POA - LIVE CAM 1 Aeroporto Salgado Filho de Porto Alegre - RS - Brasil - Movimento ao Vivo",
    place: { name: "Porto Alegre", countryCode: "BR" },
  },
  {
    id: "kingston-jamaica",
    nameJa: "キングストン（ジャマイカ）",
    nameEn: "Kingston, Jamaica",
    category: "city",
    handle: "See Jamaica ",
    channelId: "UCfS5_X4LiZJV5vq6z7itypA",
    videoId: "C71bNZ1coG4",
    titleKey: "🟢Half Way Tree Clock LIVE 24/7 – Kingston Jamaica Street Camera",
    place: { name: "Kingston", countryCode: "JM" },
  },
  {
    id: "pattaya-soi-buakhao",
    nameJa: "パタヤ ソイ・ブアカオ",
    nameEn: "Soi Buakhao, Pattaya",
    category: "city",
    handle: "ole petter løbak (ice_baby)",
    channelId: "UCd0Aa89g9hbSQC-APdXWNNg",
    videoId: "8ieVWInyYKk",
    titleKey: "Soi Buakhao, Pattaya Live, Thailand",
    place: { name: "Pattaya", countryCode: "TH" },
  },
  {
    id: "bohol-alona",
    nameJa: "ボホール島 アロナビーチ",
    nameEn: "Alona Beach, Bohol",
    category: "nature",
    handle: "투어 바스켓 (보홀)",
    channelId: "UCvcgdCvIPABMv-LOILqIHsw",
    videoId: "F4QxpMNKggI",
    titleKey: "LIVE !! 보홀 여행 필수 체크! 헤난 알로나 리조트 정문 실시간 날씨 &amp; 거리 분위기 라이브 캠 (어반스파이스)",
    place: { name: "Panglao", countryCode: "PH" },
  },
  {
    id: "sakurajima",
    nameJa: "桜島",
    nameEn: "Sakurajima Volcano",
    category: "volcano",
    handle: "財宝公式チャンネル",
    channelId: "UCpWU25qIleNLmUEF9VwBdMA",
    videoId: "PeElJClXtzE",
    titleKey: "【2K LIVE】桜島 ライブカメラB【近景】鹿児島県 垂水市 / Sakurajima, an active volcano live cam (Close-up view) JAPAN&#39;",
    at: { lat: 31.5931, lng: 130.6572, timeZone: "Asia/Tokyo", country: "JP" },
  },
  {
    id: "nagoya-hisaya",
    nameJa: "名古屋 久屋大通公園",
    nameEn: "Hisaya-odori Park, Nagoya",
    category: "city",
    handle: "トリニティーライブ",
    channelId: "UCHoJiBhfhNVyFcennfJr7Yg",
    videoId: "XveD1yUUmsE",
    titleKey: "【LIVE】久屋大通公園（名古屋市中区）ライブカメラ/Livecam HISAYA ODORI PARK in Nagoya Japan",
    place: { name: "Nagoya", countryCode: "JP" },
  },
  {
    id: "gujo-hachiman",
    nameJa: "郡上八幡",
    nameEn: "Gujo Hachiman",
    category: "city",
    handle: "郡上どっとcom",
    channelId: "UCyoue0T-ZZp8NVJ9fBAsygA",
    videoId: "L0C80aVxJaU",
    titleKey: "【岐阜県郡上市】郡上八幡 お天気カメラ LIVECAM",
    place: { name: "Gujo", countryCode: "JP" },
  },
  {
    id: "canmore-alberta",
    nameJa: "カンモア（カナダ・ロッキー）",
    nameEn: "Canmore, Alberta",
    category: "nature",
    handle: "CanmoreAlberta.com",
    channelId: "UCSB3xOs0FgIW0uqKTqoXqhg",
    videoId: "_0wPODlF9wU",
    titleKey: "Main Street Livecam, Canmore, Alberta",
    place: { name: "Canmore", countryCode: "CA", admin1: "Alberta" },
  },
  // ── 5 巡目: アラビア語・ヒンディー語・ベトナム語・インドネシア語・
  //    ギリシャ語・ポルトガル語・スウェーデン語・チェコ語・ロシア語・タイ語 ──
  //    中東と南アジアは収穫が薄かった(報道の 24 時間配信が大半)。
  //    代わりに欧州の小さな自治体・観光局と、アフリカ・日本の名所が出た。
  {
    id: "singapore-downtown",
    nameJa: "シンガポール ダウンタウン",
    nameEn: "Downtown Singapore",
    category: "city",
    handle: "SingReef",
    channelId: "UCD-Hv0aJkZz0isAwOtFErVg",
    videoId: "9cfkyMzanbc",
    titleKey: "【LIVE CAMERA】Downtown Singapore　シンガポール　ライブカメラ",
    place: { name: "Singapore", countryCode: "SG" },
  },
  {
    id: "rhine-falls",
    nameJa: "ラインの滝（スイス）",
    nameEn: "Rhine Falls, Switzerland",
    category: "nature",
    handle: "Schaffhauserland Tourismus",
    channelId: "UCuZhFhdPtslobdcZtGABKDA",
    videoId: "UCgLr29bxO8",
    titleKey: "Rhine Falls live | Rheinfall live - Webcam",
    at: { lat: 47.6779, lng: 8.6153, timeZone: "Europe/Zurich", country: "CH" },
  },
  {
    id: "mamaia-beach",
    nameJa: "ママイア海岸（ルーマニア）",
    nameEn: "Mamaia Beach, Romania",
    category: "nature",
    handle: "Webcam Romania",
    channelId: "UCIN4PXb4H-G0Pi4R2A_ZEgA",
    videoId: "1ImMAzHB2EI",
    titleKey: "Webcam Mamaia Hotel Malibu  –  LIVE de pe plajă",
    place: { name: "Mamaia", countryCode: "RO" },
  },
  {
    id: "koksijde",
    nameJa: "コクシャイデ（ベルギー）",
    nameEn: "Koksijde, Belgium",
    category: "nature",
    handle: "Koksijde-Oostduinkerke",
    channelId: "UCPAgksFpFLJDVyMcIYsbz3A",
    videoId: "5Uqw_G_IdjE",
    titleKey: "Webcam Koksijde-Bad",
    place: { name: "Koksijde", countryCode: "BE" },
  },
  {
    id: "havlickuv-brod",
    nameJa: "ハヴリーチクーフ・ブロト広場",
    nameEn: "Havlíčkův Brod Square",
    category: "city",
    handle: "Město Havlíčkův Brod - živé přenosy",
    channelId: "UC8eRoWTPlxALM729Vm854sA",
    videoId: "-ITtIF0sxRs",
    titleKey: "Havlíčkovo náměstí živě",
    place: { name: "Havlickuv Brod", countryCode: "CZ" },
  },
  {
    id: "itaura-village",
    nameJa: "イタウラ村（インド）",
    nameEn: "Itaura Village, India",
    category: "city",
    handle: "Sunil singh chauhan",
    channelId: "UChswY0TkLMxfTMQRfBpHhMQ",
    videoId: "ss7rSdSTrwc",
    titleKey: "🔴 24/7 Live: LS Jan Seva Kendra &amp; LIC Office | Itaura Village Cam",
    place: { name: "Itaura", countryCode: "IN" },
  },
  {
    id: "alma-atacama",
    nameJa: "アタカマ砂漠 ALMA望遠鏡群",
    nameEn: "ALMA Observatory, Atacama",
    category: "nature",
    handle: "Asahi Astro LIVE　朝日新聞宇宙部",
    channelId: "UCiN7OwV8g8dMm_E0xphBVig",
    videoId: "BVKRAzTSnB0",
    titleKey: "The Atacama Large Millimeter/submillimeter Array (ALMA) and Starry sky LIVE, Chile",
    at: { lat: -23.0294, lng: -67.7548, timeZone: "America/Santiago", country: "CL" },
  },
  {
    id: "porto-ribeira",
    nameJa: "ポルト リベイラ地区",
    nameEn: "Ribeira, Porto",
    category: "city",
    handle: "Webcamtaxi",
    channelId: "UC1tBnbs03VJ34oLD8cmJSVw",
    videoId: "45wxTsNFPXw",
    titleKey: "LIVE Porto Webcam Ribeira and Vila Nova de Gaia – Oporto, Portugal",
    place: { name: "Porto", countryCode: "PT" },
  },
  {
    id: "funchal-marina",
    nameJa: "フンシャル港（マデイラ島）",
    nameEn: "Funchal Marina, Madeira",
    category: "harbor",
    handle: "Madeira-Web",
    channelId: "UCH_lKz2VXlfLPgYOE3biySg",
    videoId: "f6D3Zq6J5A8",
    titleKey: "LIVE: Funchal Marina Webcam 2 Madeira Island | Madeira-Web",
    place: { name: "Funchal", countryCode: "PT" },
  },
  {
    id: "levi-lapland",
    nameJa: "レヴィ（フィンランド・ラップランド）",
    nameEn: "Levi, Finnish Lapland",
    category: "nature",
    handle: "Levi Ski Resort",
    channelId: "UC1HDQ1Q5nVHYF8e7dL4E-pw",
    videoId: "LwihxyJ4V20",
    titleKey: "Zero Point Levi | Levi Ski Resort | Finland",
    place: { name: "Kittila", countryCode: "FI" },
  },
  {
    id: "fort-william",
    nameJa: "フォート・ウィリアム（スコットランド）",
    nameEn: "Fort William, Scotland",
    category: "nature",
    handle: "Alex  Scotventure",
    channelId: "UCAY-GlV3P5twjg7B9tjx_lg",
    videoId: "2occtpoOu_w",
    titleKey: "🔴LIVE - Fort William Live Webcam - Scotland - Loch Linnhe &amp; West End Car Park",
    place: { name: "Fort William", countryCode: "GB", admin1: "Scotland" },
  },
  {
    id: "lake-windermere",
    nameJa: "ウィンダミア湖（湖水地方）",
    nameEn: "Lake Windermere",
    category: "nature",
    handle: "English Lakes Hotels, Resorts & Venues",
    channelId: "UCFaNfBC_D28ZtqBH3jfcasQ",
    videoId: "MK6MjpRLPWs",
    titleKey: "Live Webcam from Low Wood Bay Resort &amp; Spa — Lake Windermere, UK",
    place: { name: "Windermere", countryCode: "GB", admin1: "England" },
  },
  {
    id: "prague-airport",
    nameJa: "プラハ空港",
    nameEn: "Prague Airport",
    category: "airport",
    handle: "SlowTV",
    channelId: "UC3ewP9SczRIGGpDXDQvpPyQ",
    videoId: "kuOmmVkOGN8",
    titleKey: "🔴 LIVE: Planespotting at Prague Vaclav Havel Airport, Prague | 24/7 LIVE",
    place: { name: "Prague", countryCode: "CZ" },
  },
  {
    id: "amsterdam-dam",
    nameJa: "アムステルダム ダム広場",
    nameEn: "Dam Square, Amsterdam",
    category: "city",
    handle: "Now4Rent",
    channelId: "UCWsoep0hJKhGbYosMeQIyXA",
    videoId: "Gd9d4q6WvUY",
    titleKey: "Now4Rent.NL | Amsterdam De Dam | Pan Tilt Zoom Camera | Ultra HD (4K)",
    at: { lat: 52.3731, lng: 4.8926, timeZone: "Europe/Amsterdam", country: "NL" },
  },
  {
    id: "muizenberg-beach",
    nameJa: "ムイゼンバーグ海岸（ケープタウン）",
    nameEn: "Muizenberg Beach",
    category: "nature",
    handle: "REEF SOUTH AFRICA",
    channelId: "UCef_Yfk6baScsTCcDxzXE5Q",
    videoId: "-dGHAohQcSc",
    titleKey: "Muizenberg Beach Live Webcam | REEF South Africa  @Reef-SA",
    place: { name: "Muizenberg", countryCode: "ZA" },
  },
  {
    id: "clifton-beach",
    nameJa: "クリフトン海岸（ケープタウン）",
    nameEn: "Clifton Beach, Cape Town",
    category: "nature",
    handle: "SA Webcams",
    channelId: "UCLmKcWr9EjhgrlivvJQovOQ",
    videoId: "IGu55JrxyHU",
    titleKey: "Clifton 4th beach webcam Live Stream, Cape Town",
    place: { name: "Cape Town", countryCode: "ZA" },
  },
  {
    id: "zenkoji",
    nameJa: "善光寺（長野）",
    nameEn: "Zenkoji Temple, Nagano",
    category: "city",
    handle: "INC長野ケーブルテレビ 【公式】",
    channelId: "UCy9ww22FuUlXd0c6B8INJVQ",
    videoId: "HvJdPF46kak",
    titleKey: "善光寺LIVEカメラ（Zenkoji Temple Live Cam)　INC長野ケーブルテレビ",
    at: { lat: 36.6617, lng: 138.1875, timeZone: "Asia/Tokyo", country: "JP" },
  },
  {
    id: "kyoto-kiyomizuzaka",
    nameJa: "京都 清水坂",
    nameEn: "Kiyomizu-zaka, Kyoto",
    category: "city",
    handle: "京都観光混雑状況Live",
    channelId: "UCyVf8FIJ-kFpzUadi7_tgZQ",
    videoId: "cUnYPpK7ENk",
    titleKey: "【LIVE】京都 清水坂ライブ中継カメラ／Kiyomizu-zaka, Kyoto Live camera",
    at: { lat: 34.9948, lng: 135.783, timeZone: "Asia/Tokyo", country: "JP" },
  },
  {
    id: "niseko-hanazono",
    nameJa: "ニセコ 花園",
    nameEn: "Niseko Hanazono",
    category: "nature",
    handle: "Hanazono Niseko Resort ニセコ HANAZONOリゾート",
    channelId: "UCrNyeY4kGLL0-Hs8wC98peg",
    videoId: "1ksmiy6EsDo",
    titleKey: "[4K] Live Camera - Niseko Hanazono Resort",
    place: { name: "Kutchan", countryCode: "JP" },
  },
  {
    id: "beppu-bay",
    nameJa: "別府湾",
    nameEn: "Beppu Bay",
    category: "harbor",
    handle: "tyann sywei",
    channelId: "UCd41Qao7-RbhcZeDywVfZ9w",
    videoId: "hdVgObFgBV8",
    titleKey: "【4K  LIVE】Beppu Bay Cam　国道10号・別府湾　災害時の波、道路渋滞、地震、台風などの情報にお役立てください。　＃災害＃別府湾＃別大＃夕焼け",
    place: { name: "Beppu", countryCode: "JP" },
  },
  {
    id: "niagara-falls",
    nameJa: "ナイアガラの滝",
    nameEn: "Niagara Falls",
    category: "nature",
    handle: "Niagara Falls Live",
    channelId: "UC15QFO-cdISk-4Sn5CPd78g",
    videoId: "7gBzLGlJnwk",
    titleKey: "Niagara Falls Live",
    at: { lat: 43.0828, lng: -79.0742, timeZone: "America/New_York", country: "US" },
  },
  {
    id: "miami-coral-city",
    nameJa: "マイアミ 水中のサンゴ礁",
    nameEn: "Coral City Camera, Miami",
    category: "animal",
    handle: "Coral Morphologic",
    channelId: "UCtllXAWa3EcfcsL5tvpqGSw",
    videoId: "7i8ARjIeM2k",
    titleKey: "Coral City Camera (Miami&#39;s Free-Range Aquarium Underwater Livestream)",
    place: { name: "Miami", countryCode: "US", admin1: "Florida" },
  },
  {
    id: "yosemite",
    nameJa: "ヨセミテ国立公園",
    nameEn: "Yosemite National Park",
    category: "nature",
    handle: "EarthLiveTV",
    channelId: "UCScswbWVOicLBZwD_6zfXkA",
    videoId: "AvJl1Vbsg38",
    titleKey: "🏔️ Yosemite National Park LIVE | El Capitan, Half Dome &amp; Yosemite Falls",
    place: { name: "Yosemite Valley", countryCode: "US", admin1: "California" },
  },
  {
    id: "calgary",
    nameJa: "カルガリー（カナダ）",
    nameEn: "Calgary, Canada",
    category: "city",
    handle: "DELTATECH Calgary",
    channelId: "UCXab5AWv4FVoGCoVqDTq36w",
    videoId: "MwcqP3ta6RI",
    titleKey: "Calgary Live Camera",
    place: { name: "Calgary", countryCode: "CA", admin1: "Alberta" },
  },
  // ── 6 巡目: 地名を直接クエリにした ────────────────────────
  // 中東・南アジア・アフリカにはほとんど効かなかった(Dubai で検索しても
  // ニューヨークやケニアが返る。YouTube のライブ検索は地名より人気度を見る)。
  // 一方でアイスランド・ギリシャ・ネパールは名指しでよく当たった。
  {
    id: "reykjavik",
    nameJa: "レイキャヴィク",
    nameEn: "Reykjavík, Iceland",
    category: "city",
    handle: "Our World Live",
    channelId: "UCuVVqZu5AuRf3jaKHRy5-Sw",
    videoId: "tYgGEC-ESTw",
    titleKey: "Reykjavik, Iceland LIVE",
    place: { name: "Reykjavik", countryCode: "IS" },
  },
  {
    id: "iceland-eruption",
    nameJa: "アイスランドの噴火（ハガフェル）",
    nameEn: "Iceland Volcano Eruption",
    category: "volcano",
    handle: "mbl.is",
    channelId: "UCpkcJlssp52fP6xHFUYT9ag",
    videoId: "L8i9G8jhWao",
    titleKey: "LIVE from Hagafell - Close up - Iceland volcano eruption",
    place: { name: "Grindavik", countryCode: "IS" },
  },
  {
    id: "akureyri",
    nameJa: "アークレイリ（北アイスランド）",
    nameEn: "Akureyri, Iceland",
    category: "city",
    handle: "Akureyrarbær",
    channelId: "UC0aRUMUvwJ-7xx0mfNwhVZA",
    videoId: "GXTycxKz_FQ",
    titleKey: "Rósenborg",
    place: { name: "Akureyri", countryCode: "IS" },
  },
  {
    id: "ilulissat-icebergs",
    nameJa: "イルリサットの氷山（グリーンランド）",
    nameEn: "Ilulissat Icebergs, Greenland",
    category: "nature",
    handle: "afarTV",
    channelId: "UCaG0IHN1RMOZ4-U3wDXAkwA",
    videoId: "h8O0UXsL7uk",
    titleKey: "🔴 Live Now: 24/7 Iceberg Cam of Ilulissat, Greenland in 4K Ultra HD",
    place: { name: "Ilulissat", countryCode: "GL" },
  },
  {
    id: "athens",
    nameJa: "アテネ",
    nameEn: "Athens, Greece",
    category: "city",
    handle: "Αλέξανδρος Τσουράπας",
    channelId: "UCHM2Zp3HKkf2lQPItuIG6uA",
    videoId: "gf_B5-ZNByA",
    titleKey: "🟢Live Παράθυρο στην Αθήνα / Window in Athens | 4K-UHD",
    place: { name: "Athens", countryCode: "GR" },
  },
  {
    id: "tinos-port",
    nameJa: "ティノス島の港",
    nameEn: "Port of Tinos",
    category: "harbor",
    handle: "Tinos Web Tv",
    channelId: "UCGYQwxgH5Nac7xlQW6MHPAQ",
    videoId: "PAK2GoHG7Hs",
    titleKey: "Tinos live: Το λιμάνι της Τήνου - port of Tinos",
    place: { name: "Tinos", countryCode: "GR" },
  },
  {
    id: "rhodes-beach",
    nameJa: "ロードス島",
    nameEn: "Rhodes, Greece",
    category: "nature",
    handle: "Rodos Palladium Leisure & Wellness",
    channelId: "UCVwale2XH1_In8HAlZIEfOA",
    videoId: "kpyEOpLmXUk",
    titleKey: "Rodos Palladium Beach Live",
    place: { name: "Rhodes", countryCode: "GR" },
  },
  {
    id: "kathmandu",
    nameJa: "カトマンズ",
    nameEn: "Kathmandu, Nepal",
    category: "city",
    handle: "WEBCAM NEPAL CITIES & TOWNS",
    channelId: "UCp8FhsgzNmYR6F1HxTDMTvw",
    videoId: "6WWbTU6v3r0",
    titleKey: "KATHMANDU LIVE CAM 🇳🇵 | NEPAL&#39;S CAPITAL CITY LIVE | WEBCAM NEPAL",
    place: { name: "Kathmandu", countryCode: "NP" },
  },
  {
    id: "annapurna-lete",
    nameJa: "アンナプルナ（レテ村）",
    nameEn: "Annapurna, Lete",
    category: "nature",
    handle: "WEBCAM NEPAL ANNAPURNA",
    channelId: "UCbv8BrmNooNIUu9QDmOp7Qw",
    videoId: "HxUjr2fGO-M",
    titleKey: "WEBCAM NEPAL LIVE - STREAMING FROM KALOPANI GUEST HOUSE – LETE, MUSTANG, NEPAL",
    place: { name: "Lete", countryCode: "NP" },
  },
  {
    id: "bali",
    nameJa: "バリ島",
    nameEn: "Bali, Indonesia",
    category: "nature",
    handle: "Bali Weather Live Stream",
    channelId: "UCjc3XanPPTV1Ar1ec6ElXTg",
    videoId: "L1duJDAqbJY",
    titleKey: "Bali Weather Today Live Webcam | Bali Weather Now with Temperature and Humidity | Bali Weather Live",
    place: { name: "Denpasar", countryCode: "ID" },
  },
  {
    id: "arvidsjaur",
    nameJa: "アルヴィッツヤウル（スウェーデン）",
    nameEn: "Arvidsjaur, Sweden",
    category: "nature",
    handle: "Live Arvidsjaur",
    channelId: "UCo9Ppp8AjdfXqocqcNI_krA",
    videoId: "Dnw_l8f9rUc",
    titleKey: "Live Camera Arvidsjaur",
    place: { name: "Arvidsjaur", countryCode: "SE" },
  },
  {
    id: "rovaniemi-santa",
    nameJa: "ロヴァニエミ サンタクロース村",
    nameEn: "Santa Claus Village, Rovaniemi",
    category: "city",
    handle: "City of Rovaniemi",
    channelId: "UCuarPSgSklrmX2z0iA-Ua4Q",
    videoId: "Cp4RRAEgpeU",
    titleKey: "Live @ Santa Claus Village",
    place: { name: "Rovaniemi", countryCode: "FI" },
  },
  {
    id: "groningen",
    nameJa: "フローニンゲン 大広場",
    nameEn: "Grote Markt, Groningen",
    category: "city",
    handle: "Bouwwebcam - live stream & timelapse video",
    channelId: "UCoGAnM2Ek-KVDEQiyuN_XGg",
    videoId: "ZjfFGJlkjmE",
    titleKey: "Webcam Grote Markt - Groningen",
    place: { name: "Groningen", countryCode: "NL" },
  },
  {
    id: "malaga-airport",
    nameJa: "マラガ空港",
    nameEn: "Málaga Airport",
    category: "airport",
    handle: "meteo365es",
    channelId: "UCKCw1qKElfcxE6A1KefdG5A",
    videoId: "A6R81wOlQqs",
    titleKey: "🔵 LIVE from Malaga Airport (AGP/LEMG) - Costa del Sol - Andalucía - Spain - 24/7",
    place: { name: "Malaga", countryCode: "ES" },
  },
  {
    id: "alghero-beach",
    nameJa: "アルゲーロ（サルデーニャ島）",
    nameEn: "Alghero, Sardinia",
    category: "nature",
    handle: "World Cams",
    channelId: "UC04KebJjRJz9Fo5-SF9VfeA",
    videoId: "kGO2F0KogFQ",
    titleKey: "🔴Maia Pia Beach - Sardinia, Italy - Live Cam",
    place: { name: "Alghero", countryCode: "IT" },
  },
  {
    id: "victoria-bc",
    nameJa: "ヴィクトリア（カナダ BC州）",
    nameEn: "Victoria, British Columbia",
    category: "harbor",
    handle: "Ross Bay Live Webcam",
    channelId: "UCcoQfizLr4MYgiAkkYnQobA",
    videoId: "sLixr8cThJo",
    titleKey: "Ross Bay, Victoria BC",
    place: { name: "Victoria", countryCode: "CA", admin1: "British Columbia" },
  },
];
