// discover-cams.ts が集めた候補のうち、地理が一意に定まるものだけを人手で選び、
// 場所の情報を与えた表。これが src/data/cams.ts の元になる。
//
// 座標の出どころは 2 通りで、どちらも「記憶で書いた数字」にしないのが方針:
//   place … Open-Meteo のジオコーディングで解決する(小さな町はこちら。町の中心が
//           実質そのままカメラの位置になる)。admin1 は同名地の取り違え防止。
//   at    … 誰でも地図で確かめられる著名なランドマークだけ、明示的に置く。

import type { CamCategory } from "../src/domain/cams";

export interface PlaceQuery {
  name: string;
  countryCode: string;
  /** 州・県名。同名の町を取り違えないための絞り込み。 */
  admin1?: string;
}

export interface CamPlace {
  id: string;
  nameJa: string;
  nameEn: string;
  category: CamCategory;
  /** discover-cams.ts の出力にあるチャンネル(ハンドル)。 */
  handle: string;
  videoId: string;
  place?: PlaceQuery;
  at?: { lat: number; lng: number; timeZone: string; country: string };
}

export const CAM_PLACES: CamPlace[] = [
  // ── 日本 ────────────────────────────────────────────────
  {
    id: "shibuya-crossing",
    nameJa: "渋谷スクランブル交差点",
    nameEn: "Shibuya Scramble Crossing",
    category: "city",
    handle: "ANNnewsCH",
    videoId: "8H3nRCFVR6Y",
    at: { lat: 35.6595, lng: 139.7005, timeZone: "Asia/Tokyo", country: "JP" },
  },
  {
    id: "shinjuku-station",
    nameJa: "新宿駅前",
    nameEn: "Shinjuku Station",
    category: "city",
    handle: "tbsnewsdig",
    videoId: "BePkAsZnDjM",
    at: { lat: 35.6900, lng: 139.7004, timeZone: "Asia/Tokyo", country: "JP" },
  },
  {
    id: "haneda-terminal-2",
    nameJa: "羽田空港 第2ターミナル",
    nameEn: "Haneda Airport Terminal 2",
    category: "airport",
    handle: "ANNnewsCH",
    videoId: "OyWPJhU-iI8",
    at: { lat: 35.5494, lng: 139.7798, timeZone: "Asia/Tokyo", country: "JP" },
  },
  {
    id: "haneda-terminal-1",
    nameJa: "羽田空港 第1ターミナル",
    nameEn: "Haneda Airport Terminal 1",
    category: "airport",
    handle: "tbsnewsdig",
    videoId: "2f9NOSw-FqM",
    at: { lat: 35.5490, lng: 139.7855, timeZone: "Asia/Tokyo", country: "JP" },
  },

  // ── ヨーロッパ ──────────────────────────────────────────
  {
    id: "venice-san-marco",
    nameJa: "ヴェネツィア サン・マルコ広場",
    nameEn: "Venice, St Mark's Square",
    category: "city",
    handle: "SkylineWebcams",
    videoId: "x4AlaibltlA",
    at: { lat: 45.4341, lng: 12.3388, timeZone: "Europe/Rome", country: "IT" },
  },
  {
    id: "abbey-road-crossing",
    nameJa: "アビイ・ロードの横断歩道",
    nameEn: "Abbey Road Crossing",
    category: "city",
    handle: "EarthCam",
    videoId: "zMCea32gpmg",
    at: { lat: 51.5320, lng: -0.1779, timeZone: "Europe/London", country: "GB" },
  },
  {
    id: "mallorca",
    nameJa: "マヨルカ島",
    nameEn: "Mallorca",
    category: "harbor",
    handle: "EarthCam",
    videoId: "jtdyLykT_XY",
    place: { name: "Palma", countryCode: "ES", admin1: "Balearic Islands" },
  },

  // ── 北米 (都市・ランドマーク) ───────────────────────────
  {
    id: "times-square",
    nameJa: "タイムズスクエア",
    nameEn: "Times Square",
    category: "city",
    handle: "EarthCam",
    videoId: "JQ_jwk_7OVE",
    at: { lat: 40.7580, lng: -73.9855, timeZone: "America/New_York", country: "US" },
  },
  {
    id: "statue-of-liberty",
    nameJa: "自由の女神(冠のカメラ)",
    nameEn: "Statue of Liberty CrownCam",
    category: "city",
    handle: "EarthCam",
    videoId: "YHRYOL03ydw",
    at: { lat: 40.6892, lng: -74.0445, timeZone: "America/New_York", country: "US" },
  },
  {
    id: "world-trade-center",
    nameJa: "ワールドトレードセンター",
    nameEn: "World Trade Center",
    category: "city",
    handle: "EarthCam",
    videoId: "5C9oM7C2Q9k",
    at: { lat: 40.7127, lng: -74.0134, timeZone: "America/New_York", country: "US" },
  },
  {
    id: "lincoln-harbor",
    nameJa: "リンカーン・ハーバー(マンハッタン対岸)",
    nameEn: "Lincoln Harbor",
    category: "harbor",
    handle: "EarthCam",
    videoId: "f_pX8XheLbY",
    at: { lat: 40.7690, lng: -74.0170, timeZone: "America/New_York", country: "US" },
  },
  {
    id: "white-house",
    nameJa: "ホワイトハウス",
    nameEn: "The White House",
    category: "city",
    handle: "earthTV",
    videoId: "5p_KGD4fJZs",
    at: { lat: 38.8977, lng: -77.0365, timeZone: "America/New_York", country: "US" },
  },
  {
    id: "washington-monument",
    nameJa: "ワシントン記念塔",
    nameEn: "Washington Monument",
    category: "city",
    handle: "EarthCam",
    videoId: "oDCAAfOSqvA",
    at: { lat: 38.8895, lng: -77.0353, timeZone: "America/New_York", country: "US" },
  },
  {
    id: "independence-hall",
    nameJa: "独立記念館とリバティ・ベル",
    nameEn: "Liberty Bell & Independence Hall",
    category: "city",
    handle: "EarthCam",
    videoId: "F1EQEDL4ddU",
    at: { lat: 39.9489, lng: -75.1500, timeZone: "America/New_York", country: "US" },
  },
  {
    id: "wrigley-field",
    nameJa: "リグレー・フィールド(シカゴ)",
    nameEn: "Wrigley Field",
    category: "city",
    handle: "EarthCam",
    videoId: "m38n8jVPUJ8",
    at: { lat: 41.9484, lng: -87.6553, timeZone: "America/Chicago", country: "US" },
  },
  {
    id: "new-orleans-balcony",
    nameJa: "ニューオーリンズ(バルコニーからの眺め)",
    nameEn: "New Orleans Balcony View",
    category: "city",
    handle: "EarthCam",
    videoId: "6lFBKxt8kIo",
    place: { name: "New Orleans", countryCode: "US", admin1: "Louisiana" },
  },
  {
    id: "flight-93-memorial",
    nameJa: "ユナイテッド93便記念碑",
    nameEn: "Flight 93 Memorial",
    category: "nature",
    handle: "EarthCam",
    videoId: "mjzA1Yxh7ZY",
    place: { name: "Shanksville", countryCode: "US", admin1: "Pennsylvania" },
  },
  {
    id: "madison-indiana",
    nameJa: "マディソン(インディアナ)",
    nameEn: "Madison, Indiana",
    category: "city",
    handle: "EarthCam",
    videoId: "Ez6xC43MMTQ",
    place: { name: "Madison", countryCode: "US", admin1: "Indiana" },
  },
  {
    id: "council-bluffs",
    nameJa: "カウンシルブラフス(アイオワ)",
    nameEn: "Council Bluffs, Iowa",
    category: "city",
    handle: "EarthCam",
    videoId: "qsrevo5Vdkw",
    place: { name: "Council Bluffs", countryCode: "US", admin1: "Iowa" },
  },
  {
    id: "jamestown-buffalo",
    nameJa: "世界最大のバッファロー像(ジェームズタウン)",
    nameEn: "World's Largest Buffalo Monument",
    category: "city",
    handle: "EarthCam",
    videoId: "VWDi2Po3ZsQ",
    place: { name: "Jamestown", countryCode: "US", admin1: "North Dakota" },
  },
  {
    id: "roswell",
    nameJa: "ロズウェル(ニューメキシコ)",
    nameEn: "Roswell, New Mexico",
    category: "city",
    handle: "EarthCam",
    videoId: "kLoFxVhRWtQ",
    place: { name: "Roswell", countryCode: "US", admin1: "New Mexico" },
  },
  {
    id: "ruidoso",
    nameJa: "ルイドソ(ニューメキシコ)",
    nameEn: "Ruidoso, New Mexico",
    category: "nature",
    handle: "EarthCam",
    videoId: "XoANQufSSXY",
    place: { name: "Ruidoso", countryCode: "US", admin1: "New Mexico" },
  },

  // ── 北米 (自然・海) ────────────────────────────────────
  {
    id: "sanibel-island",
    nameJa: "サニベル島",
    nameEn: "Sanibel Island",
    category: "nature",
    handle: "EarthCam",
    videoId: "4LTSTw4jnZc",
    place: { name: "Sanibel", countryCode: "US", admin1: "Florida" },
  },
  {
    id: "anglins-pier",
    nameJa: "アングリンズ桟橋(フロリダ)",
    nameEn: "Anglins Pier",
    category: "harbor",
    handle: "EarthCam",
    videoId: "aPo-gk0y9tg",
    place: { name: "Lauderdale-by-the-Sea", countryCode: "US", admin1: "Florida" },
  },
  {
    id: "seaside-heights",
    nameJa: "シーサイドハイツ(ニュージャージー)",
    nameEn: "Seaside Heights, NJ",
    category: "nature",
    handle: "EarthCam",
    videoId: "OBgCrw-IyhE",
    place: { name: "Seaside Heights", countryCode: "US", admin1: "New Jersey" },
  },
  {
    id: "wildwood",
    nameJa: "ワイルドウッド(ニュージャージー)",
    nameEn: "Wildwood, NJ",
    category: "nature",
    handle: "EarthCam",
    videoId: "cK71xhMRtds",
    place: { name: "Wildwood", countryCode: "US", admin1: "New Jersey" },
  },
  {
    id: "spirit-lake",
    nameJa: "スピリット湖(アイオワ)",
    nameEn: "Spirit Lake, Iowa",
    category: "nature",
    handle: "EarthCam",
    videoId: "XIe9vQkAd7Q",
    place: { name: "Spirit Lake", countryCode: "US", admin1: "Iowa" },
  },

  // ── 北米 (動物) ────────────────────────────────────────
  {
    id: "monterey-sea-otter",
    nameJa: "モントレー湾水族館 ラッコ",
    nameEn: "Monterey Bay Aquarium — Sea Otters",
    category: "animal",
    handle: "MontereyBayAquarium",
    videoId: "abbR-Ttd-cA",
    at: { lat: 36.6182, lng: -121.9018, timeZone: "America/Los_Angeles", country: "US" },
  },
  {
    id: "monterey-bay",
    nameJa: "モントレー湾",
    nameEn: "Monterey Bay",
    category: "nature",
    handle: "MontereyBayAquarium",
    videoId: "fVa6-zCBR7A",
    at: { lat: 36.6182, lng: -121.9018, timeZone: "America/Los_Angeles", country: "US" },
  },
  {
    id: "baltimore-aquarium",
    nameJa: "ボルチモア水族館",
    nameEn: "National Aquarium, Baltimore",
    category: "animal",
    handle: "EarthCam",
    videoId: "KSxc-N67TU4",
    place: { name: "Baltimore", countryCode: "US", admin1: "Maryland" },
  },
  {
    id: "greenville-giraffe",
    nameJa: "グリーンビル動物園 キリン",
    nameEn: "Greenville Zoo — Giraffes",
    category: "animal",
    handle: "EarthCam",
    videoId: "sLRtUoPNH2k",
    place: { name: "Greenville", countryCode: "US", admin1: "South Carolina" },
  },
  {
    id: "gaylord-wildlife",
    nameJa: "ゲイロード(ミシガン)の野生動物",
    nameEn: "Gaylord Wildlife Cam",
    category: "animal",
    handle: "EarthCam",
    videoId: "IU_-Pl9O5jQ",
    place: { name: "Gaylord", countryCode: "US", admin1: "Michigan" },
  },

  // ── アフリカ・南米 ──────────────────────────────────────
  {
    id: "chobe-waterhole",
    nameJa: "チョベ(ボツワナ)の水場",
    nameEn: "Chobe Watering Hole, Botswana",
    category: "animal",
    handle: "EarthCam",
    videoId: "iqdRLSdSjWI",
    place: { name: "Kasane", countryCode: "BW" },
  },
  {
    id: "rio-negro-amazon",
    nameJa: "アマゾン ネグロ川",
    nameEn: "Rio Negro, Amazon",
    category: "nature",
    handle: "ANNnewsCH",
    videoId: "zAZ6S9pv0jA",
    place: { name: "Manaus", countryCode: "BR" },
  },

  // ── メキシコ ───────────────────────────────────────────
  {
    id: "popocatepetl",
    nameJa: "ポポカテペトル山",
    nameEn: "Popocatépetl Volcano",
    category: "volcano",
    handle: "webcamsdemexico",
    videoId: "z1DIktum4zo",
    at: { lat: 19.0224, lng: -98.6279, timeZone: "America/Mexico_City", country: "MX" },
  },
  {
    id: "cdmx-zocalo",
    nameJa: "メキシコシティ ソカロ広場",
    nameEn: "Zócalo, Mexico City",
    category: "city",
    handle: "webcamsdemexico",
    videoId: "qP-b5q9u018",
    at: { lat: 19.4326, lng: -99.1332, timeZone: "America/Mexico_City", country: "MX" },
  },
  {
    id: "cdmx-angel",
    nameJa: "独立記念塔(メキシコシティ)",
    nameEn: "Ángel de la Independencia",
    category: "city",
    handle: "webcamsdemexico",
    videoId: "ZH3jB650mcI",
    at: { lat: 19.4270, lng: -99.1677, timeZone: "America/Mexico_City", country: "MX" },
  },
  {
    id: "basilica-guadalupe",
    nameJa: "グアダルーペ聖堂",
    nameEn: "Basilica of Guadalupe",
    category: "city",
    handle: "webcamsdemexico",
    videoId: "NmHkMgNwawg",
    at: { lat: 19.4847, lng: -99.1177, timeZone: "America/Mexico_City", country: "MX" },
  },

  // ── ジャクソンホール周辺(ワイオミング・モンタナ) ────────
  {
    id: "jackson-town-square",
    nameJa: "ジャクソン タウンスクエア",
    nameEn: "Jackson Town Square",
    category: "city",
    handle: "SeeJH",
    videoId: "B_waF26In9o",
    at: { lat: 43.4799, lng: -110.7624, timeZone: "America/Denver", country: "US" },
  },
  {
    id: "grand-teton",
    nameJa: "グランドティトン国立公園",
    nameEn: "Grand Teton National Park",
    category: "nature",
    handle: "SeeJH",
    videoId: "j-0fhrHzEiM",
    at: { lat: 43.7412, lng: -110.8025, timeZone: "America/Denver", country: "US" },
  },
  {
    id: "yellowstone-river-gardiner",
    nameJa: "イエローストーン川(ガーディナー)",
    nameEn: "Yellowstone River at Gardiner",
    category: "nature",
    handle: "SeeJH",
    videoId: "IvZ22jZgvOI",
    place: { name: "Gardiner", countryCode: "US", admin1: "Montana" },
  },
  {
    id: "grand-targhee",
    nameJa: "グランドターギー(アイダホ)",
    nameEn: "Grand Targhee Resort",
    category: "nature",
    handle: "SeeJH",
    videoId: "fQiA_DZT0cE",
    place: { name: "Driggs", countryCode: "US", admin1: "Idaho" },
  },

  // ── 鉄道 ───────────────────────────────────────────────
  {
    id: "rail-plant-city",
    nameJa: "プラントシティ(フロリダ)の線路",
    nameEn: "Plant City, Florida",
    category: "railway",
    handle: "VirtualRailfan",
    videoId: "IVSoVgGXDoU",
    place: { name: "Plant City", countryCode: "US", admin1: "Florida" },
  },
  {
    id: "rail-folkston",
    nameJa: "フォルクストン(ジョージア)の線路",
    nameEn: "Folkston, Georgia",
    category: "railway",
    handle: "VirtualRailfan",
    videoId: "7DmivRg6FfQ",
    place: { name: "Folkston", countryCode: "US", admin1: "Georgia" },
  },
  {
    id: "rail-saint-louis",
    nameJa: "セントルイスの線路",
    nameEn: "Saint Louis, Missouri",
    category: "railway",
    handle: "VirtualRailfan",
    videoId: "9eqVB3JbJHc",
    place: { name: "St. Louis", countryCode: "US", admin1: "Missouri" },
  },
  {
    id: "rail-cresson",
    nameJa: "クレッソン(ペンシルベニア)の線路",
    nameEn: "Cresson, Pennsylvania",
    category: "railway",
    handle: "VirtualRailfan",
    videoId: "9uPCPh8jWas",
    place: { name: "Cresson", countryCode: "US", admin1: "Pennsylvania" },
  },
  {
    id: "rail-salt-lake-city",
    nameJa: "ソルトレイクシティの線路",
    nameEn: "Salt Lake City, Utah",
    category: "railway",
    handle: "VirtualRailfan",
    videoId: "qJd7diix4eI",
    place: { name: "Salt Lake City", countryCode: "US", admin1: "Utah" },
  },
  {
    id: "rail-cheyenne",
    nameJa: "シャイアン(ワイオミング)の線路",
    nameEn: "Cheyenne, Wyoming",
    category: "railway",
    handle: "VirtualRailfan",
    videoId: "hV30GxkdTAs",
    place: { name: "Cheyenne", countryCode: "US", admin1: "Wyoming" },
  },
  {
    id: "rail-quanah",
    nameJa: "クアナ(テキサス)の線路",
    nameEn: "Quanah, Texas",
    category: "railway",
    handle: "VirtualRailfan",
    videoId: "LInPY_D1Ln4",
    place: { name: "Quanah", countryCode: "US", admin1: "Texas" },
  },
  {
    id: "rail-jesup",
    nameJa: "ジェサップ(ジョージア)の線路",
    nameEn: "Jesup, Georgia",
    category: "railway",
    handle: "VirtualRailfan",
    videoId: "1AOrlYblQR8",
    place: { name: "Jesup", countryCode: "US", admin1: "Georgia" },
  },
  {
    id: "rail-seattle",
    nameJa: "シアトルの線路",
    nameEn: "Seattle, Washington",
    category: "railway",
    handle: "VirtualRailfan",
    videoId: "pHqTDmH7H7c",
    place: { name: "Seattle", countryCode: "US", admin1: "Washington" },
  },
  {
    id: "rail-deshler",
    nameJa: "デシュラー(オハイオ)の線路",
    nameEn: "Deshler, Ohio",
    category: "railway",
    handle: "VirtualRailfan",
    videoId: "TjMwpB8JRw8",
    place: { name: "Deshler", countryCode: "US", admin1: "Ohio" },
  },
  {
    id: "rail-la-grange",
    nameJa: "ラグレンジ(ケンタッキー)の線路",
    nameEn: "La Grange, Kentucky",
    category: "railway",
    handle: "VirtualRailfan",
    videoId: "OtssjZ3hdX0",
    place: { name: "La Grange", countryCode: "US", admin1: "Kentucky" },
  },
  {
    id: "rail-tucson",
    nameJa: "ツーソン(アリゾナ)の線路",
    nameEn: "Tucson, Arizona",
    category: "railway",
    handle: "VirtualRailfan",
    videoId: "q5BQRwSh41Q",
    place: { name: "Tucson", countryCode: "US", admin1: "Arizona" },
  },
  {
    id: "rail-cumberland",
    nameJa: "カンバーランド(メリーランド)の線路",
    nameEn: "Cumberland, Maryland",
    category: "railway",
    handle: "VirtualRailfan",
    videoId: "cR3kSHm7Ts0",
    place: { name: "Cumberland", countryCode: "US", admin1: "Maryland" },
  },
  {
    id: "rail-battle-creek",
    nameJa: "バトルクリーク(ミシガン)の線路",
    nameEn: "Battle Creek, Michigan",
    category: "railway",
    handle: "VirtualRailfan",
    videoId: "m3iasBkPAbo",
    place: { name: "Battle Creek", countryCode: "US", admin1: "Michigan" },
  },
  {
    id: "rail-ashland",
    nameJa: "アシュランド(バージニア)の線路",
    nameEn: "Ashland, Virginia",
    category: "railway",
    handle: "VirtualRailfan",
    videoId: "_eArnSLGhSo",
    place: { name: "Ashland", countryCode: "US", admin1: "Virginia" },
  },
  {
    id: "rail-cordele",
    nameJa: "コーデル(ジョージア)の線路",
    nameEn: "Cordele, Georgia",
    category: "railway",
    handle: "VirtualRailfan",
    videoId: "ll3X1mH_g9Q",
    place: { name: "Cordele", countryCode: "US", admin1: "Georgia" },
  },
];
